//##using System;
//##using System.Linq;
//##using DTOMaker.SrcGen.Core;
//##namespace DTOMaker.SrcGen.MsgPack2;
//###pragma warning disable CS0162 // Unreachable code detected
//##public sealed class EntityGenerator : EntityGeneratorBase
//##{
//##    public EntityGenerator(SourceGeneratorParameters parameters) : base(parameters) { }
//##    protected override void OnGenerate(OutputEntity entity)
//##    {
//##        using var entityScope = NewScope(entity);
// <copyright>
//     Copyright (c) T_CopyrightYear_. All rights reserved by T_CopyrightOwner_.
// </copyright>
// <auto-generated>
//     This source file was generated by a DTOMaker source generator. Changes made to this file will be lost
//     if re-generated. For further information, refer to: https://github.com/datafac/dtomaker-all.
// </auto-generated>
#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#nullable enable
using DataFac.Memory;
using DTOMaker.Models;
using DTOMaker.Runtime.MsgPack2;
using MessagePack;
using System;

//##if (false) {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS0618 // Type or member is obsolete
using T_CustomMemberType_ = System.DayOfWeek;
using T_NativeMemberType_ = System.Int32;
namespace T_MemberTypeImplSpace_
{
    [MessagePackObject]
    public sealed class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_, IEquatable<T_MemberTypeImplName_>
    {
        private static readonly T_MemberTypeImplName_ _empty = new T_MemberTypeImplName_();
        public static T_MemberTypeImplName_ Empty => _empty;

        public static T_MemberTypeImplName_ CreateFrom(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) => throw new NotImplementedException();
        protected override int OnGetEntityId() => 3;
        public T_MemberTypeImplName_() { }
        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) { }
        protected override IEntityBase OnPartCopy() => throw new NotImplementedException();

        [Key(1)]
        public long Field1 { get; set; }

        public bool Equals(T_MemberTypeImplName_? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            if (!base.Equals(other)) return false;
            if (other.Field1 != Field1) return false;
            return true;
        }

        public override bool Equals(object? obj) => obj is T_MemberTypeImplName_ other && Equals(other);
        public override int GetHashCode() => HashCode.Combine(Field1);
        public static bool operator ==(T_MemberTypeImplName_? left, T_MemberTypeImplName_? right) => left is not null ? left.Equals(right) : (right is null);
        public static bool operator !=(T_MemberTypeImplName_? left, T_MemberTypeImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);
    }
}
namespace T_BaseImplNameSpace_
{
    [MessagePackObject]
    [Union(T_ImplNameSpace_.T_ConcreteEntity_.EntityId, typeof(T_ImplNameSpace_.T_ConcreteEntity_))]
    public abstract class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>
    {
        public T_BaseImplName_() { }
        public T_BaseImplName_(T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(source) { }
        public T_BaseImplName_(T_BaseImplName_ source) : base(source) { }

        [Key(1)] public T_NativeMemberType_ BaseField1 { get; set; }

        public bool Equals(T_BaseImplName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_BaseImplName_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
//##}
namespace T_ImplNameSpace_
{
    //##if (entity.DerivedEntities.Count > 0) {
    /// <summary>
    /// Abstract class T_AbstractEntity_
    /// </summary>
    [MessagePackObject]
    [Union(T_AbstractEntity_.EntityId, typeof(T_AbstractEntity__Default))]
    //##foreach (var derived in entity.DerivedEntities) {
    //##using var _ = NewScope(derived);
    //##if (derived.DerivedEntities.Count == 0) {
    [Union(T_ConcreteEntity_.EntityId, typeof(T_ConcreteEntity_))]
    //##}
    //##}
    public abstract partial class T_AbstractEntity_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_AbstractEntity_>
    {
        //##if (false) {
        private const string T_MemberObsoleteMessage_ = null;
        private const bool T_MemberObsoleteIsError_ = false;
        private const int T_EntityId_ = 2;
        private const int KeyOffset = 10;
        private const int T_NullableCustomStructMemberKey_ = KeyOffset + 1;
        private const int T_NullableNativeStructMemberKey_ = KeyOffset + 2;
        private const int T_RequiredCustomStructMemberKey_ = KeyOffset + 3;
        private const int T_RequiredNativeStructMemberKey_ = KeyOffset + 4;
        private const int T_NullableEntityMemberKey_ = KeyOffset + 5;
        private const int T_RequiredEntityMemberKey_ = KeyOffset + 6;
        private const int T_NullableBinaryMemberKey_ = KeyOffset + 7;
        private const int T_RequiredBinaryMemberKey_ = KeyOffset + 8;
        private const int T_NullableStringMemberKey_ = KeyOffset + 9;
        private const int T_RequiredStringMemberKey_ = KeyOffset + 10;
        private const int T_MemberDefaultValue_ = 0;
        //##}

        /// <summary>
        /// Represents the unique identifier for the entity type associated with this class.
        /// </summary>
        public new const int EntityId = T_EntityId_;
        /// <summary>
        /// Gets a default empty concrete entity derived from this abstract entity.
        /// </summary>
        public static new T_AbstractEntity_ Empty => T_AbstractEntity__Default.Empty;
        /// <summary>
        /// Creates a new instance of the entity from the specified source, or returns the source if it is already
        /// frozen.
        /// </summary>
        public new static T_ConcreteEntity_ CreateFrom(T_ConcreteEntity_ source)
        {
            if (source.IsFrozen) return source;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                //##if (derived.DerivedEntities.Count == 0) {
                T_ImplNameSpace_.T_ConcreteEntity_ source2 => new T_ImplNameSpace_.T_ConcreteEntity_(source2),
                //##}
                //##}
                _ => throw new ArgumentException($"Unexpected type: {source.GetType().Name}", nameof(source))
            };
        }

        /// <summary>
        /// Creates a new instance of the concrete entity from the specified source entity, or returns the source if it
        /// is already a frozen concrete entity.
        /// </summary>
        public new static T_ConcreteEntity_ CreateFrom(T_IntfNameSpace_.T_EntityIntfName_ source)
        {
            if (source is T_ConcreteEntity_ concrete && concrete.IsFrozen) return concrete;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                //##if (derived.DerivedEntities.Count == 0) {
                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_ConcreteEntity_(source2),
                //##}
                //##}
                _ => throw new ArgumentException($"Unexpected type: {source.GetType().Name}", nameof(source))
            };
        }

        /// <summary>
        /// Creates a new instance of the concrete entity by deserializing the specified buffer, if the provided entity
        /// identifier matches the expected value.
        /// </summary>
        public new static T_ConcreteEntity_ CreateFrom(int entityId, ReadOnlyMemory<byte> buffer)
        {
            return entityId switch
            {
                //##foreach (var derived in entity.DerivedEntities) {
                //##using var _ = NewScope(derived);
                //##if (derived.DerivedEntities.Count == 0) {
                T_ImplNameSpace_.T_ConcreteEntity_.EntityId => buffer.DeserializeFromMessagePack<T_ImplNameSpace_.T_ConcreteEntity_>(),
                //##}
                //##}
                _ => throw new ArgumentOutOfRangeException(nameof(entityId), entityId, null)
            };
        }

        /// <inheritdoc/>
        protected override int OnGetEntityId() => T_EntityId_;

        /// <inheritdoc/>
        protected override void OnFreeze()
        {
            base.OnFreeze();
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_?.Freeze();
            //##} else {
            _T_RequiredEntityMemberName_.Freeze();
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##break;
            //##case MemberKind.String:
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        /// <summary>
        /// Initializes a new instance of the T_AbstractEntity_ class.
        /// </summary>
        protected T_AbstractEntity_() { }

        /// <summary>
        /// Initializes a new instance of the T_AbstractEntity_ class by copying the values from the specified source.
        /// </summary>
        protected T_AbstractEntity_(T_AbstractEntity_ source) : base(source)
        {
            if (source is null) throw new ArgumentNullException(nameof(source));
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            _T_NullableCustomStructMemberName_ = source._T_NullableCustomStructMemberName_;
            //##} else {
            _T_NullableNativeStructMemberName_ = source._T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            _T_RequiredCustomStructMemberName_ = source._T_RequiredCustomStructMemberName_;
            //##} else {
            _T_RequiredNativeStructMemberName_ = source._T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source._T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source._T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        /// <summary>
        /// Initializes a new instance of the T_AbstractEntity_ class by copying values from the specified source entity
        /// interface.
        /// </summary>
        public T_AbstractEntity_(T_IntfNameSpace_.T_EntityIntfName_ source) : base(source)
        {
            if (source is null) throw new ArgumentNullException(nameof(source));
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            _T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_NullableCustomStructMemberName_);
            //##} else {
            _T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            _T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_RequiredCustomStructMemberName_);
            //##} else {
            _T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //##switch(member.Kind) {
        //##case MemberKind.Struct:
        //##if (member.IsNullable) {
        //##if (member.IsCustom) {
        [IgnoreMember]
        private T_NativeMemberType_? _T_NullableCustomStructMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableCustomStructMemberKey_)]
        public T_NativeMemberType_? Native_T_NullableCustomStructMemberName_
        {
            get => _T_NullableCustomStructMemberName_;
            set => _T_NullableCustomStructMemberName_ = IfNotFrozen(value);
        }
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [IgnoreMember]
        public T_CustomMemberType_? T_NullableCustomStructMemberName_
        {
            get => T_ConverterSpace_.T_ConverterName_.ToCustom(Native_T_NullableCustomStructMemberName_);
            set => Native_T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(value);
        }
        //##} else {
        [IgnoreMember]
        private T_NativeMemberType_? _T_NullableNativeStructMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableNativeStructMemberKey_)]
        public T_NativeMemberType_? T_NullableNativeStructMemberName_
        {
            get => _T_NullableNativeStructMemberName_;
            set => _T_NullableNativeStructMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##} else {
        //##if (member.IsCustom) {
        [IgnoreMember]
        private T_NativeMemberType_ _T_RequiredCustomStructMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredCustomStructMemberKey_)]
        public T_NativeMemberType_ Native_T_RequiredCustomStructMemberName_
        {
            get => _T_RequiredCustomStructMemberName_;
            set => _T_RequiredCustomStructMemberName_ = IfNotFrozen(value);
        }
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [IgnoreMember]
        public T_CustomMemberType_ T_RequiredCustomStructMemberName_
        {
            get => T_ConverterSpace_.T_ConverterName_.ToCustom(Native_T_RequiredCustomStructMemberName_);
            set => Native_T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(value);
        }
        //##} else {
        [IgnoreMember]
        private T_NativeMemberType_ _T_RequiredNativeStructMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredNativeStructMemberKey_)]
        public T_NativeMemberType_ T_RequiredNativeStructMemberName_
        {
            get => _T_RequiredNativeStructMemberName_;
            set => _T_RequiredNativeStructMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##}
        //##break;
        //##case MemberKind.Entity:
        //##if (member.IsNullable) {
        [IgnoreMember]
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableEntityMemberKey_)]
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_
        {
            get => _T_NullableEntityMemberName_;
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_
        {
            get => _T_NullableEntityMemberName_;
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));
        }
        //##} else {
        [IgnoreMember]
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_ _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.Empty;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredEntityMemberKey_)]
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_
        {
            get => _T_RequiredEntityMemberName_;
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_
        {
            get => _T_RequiredEntityMemberName_;
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));
        }
        //##}
        //##break;
        //##case MemberKind.Binary:
        //##if (member.IsNullable) {
        [IgnoreMember]
        private Octets? _T_NullableBinaryMemberName_;
        //##if (member.IsObsolete) {
        /// <inheritdoc/>
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableBinaryMemberKey_)]
        public Octets? T_NullableBinaryMemberName_
        {
            get => _T_NullableBinaryMemberName_;
            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        [IgnoreMember]
        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredBinaryMemberKey_)]
        public Octets T_RequiredBinaryMemberName_
        {
            get => _T_RequiredBinaryMemberName_;
            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##case MemberKind.String:
        //##if (member.IsNullable) {
        [IgnoreMember]
        private string? _T_NullableStringMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableStringMemberKey_)]
        public string? T_NullableStringMemberName_
        {
            get => _T_NullableStringMemberName_;
            set => _T_NullableStringMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        [IgnoreMember]
        private string _T_RequiredStringMemberName_ = string.Empty;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredStringMemberKey_)]
        public string T_RequiredStringMemberName_
        {
            get => _T_RequiredStringMemberName_;
            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##default:
        //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
        //##break;
        //##} // switch

        //##}

        /// <inheritdoc/>
        public bool Equals(T_AbstractEntity_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            if (_T_NullableCustomStructMemberName_ != other._T_NullableCustomStructMemberName_) return false;
            //##} else {
            if (_T_NullableNativeStructMemberName_ != other._T_NullableNativeStructMemberName_) return false;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            if (_T_RequiredCustomStructMemberName_ != other._T_RequiredCustomStructMemberName_) return false;
            //##} else {
            if (_T_RequiredNativeStructMemberName_ != other._T_RequiredNativeStructMemberName_) return false;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            if (_T_NullableEntityMemberName_ != other.T_NullableEntityMemberName_) return false;
                              //##} else {
            if (_T_RequiredEntityMemberName_ != other.T_RequiredEntityMemberName_) return false;
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            if (_T_NullableBinaryMemberName_ != other._T_NullableBinaryMemberName_) return false;
            //##} else {
            if (_T_RequiredBinaryMemberName_ != other. _T_RequiredBinaryMemberName_) return false;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            if (!string.Equals(_T_NullableStringMemberName_, other._T_NullableStringMemberName_)) return false;
            //##} else {
            if (!string.Equals(_T_RequiredStringMemberName_, other._T_RequiredStringMemberName_)) return false;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
            return true;
        }

        /// <inheritdoc/>
        public override bool Equals(object? obj) => obj is T_AbstractEntity_ other && Equals(other);
        /// <inheritdoc/>
        public static bool operator ==(T_AbstractEntity_? left, T_AbstractEntity_? right) => left is not null ? left.Equals(right) : (right is null);
        /// <inheritdoc/>
        public static bool operator !=(T_AbstractEntity_? left, T_AbstractEntity_? right) => left is not null ? !left.Equals(right) : (right is not null);

        private int CalcHashCode()
        {
            HashCode result = new HashCode();
            result.Add(typeof(T_AbstractEntity_));
            result.Add(base.GetHashCode());
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            result.Add(_T_NullableCustomStructMemberName_);
            //##} else {
            result.Add(_T_NullableNativeStructMemberName_);
            //##}
            //##} else {
            //##if (member.IsCustom) {
            result.Add(_T_RequiredCustomStructMemberName_);
            //##} else {
            result.Add(_T_RequiredNativeStructMemberName_);
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            result.Add(_T_NullableEntityMemberName_);
            //##} else {
            result.Add(_T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            result.Add(_T_NullableBinaryMemberName_);
            //##} else {
            result.Add(_T_RequiredBinaryMemberName_);
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            result.Add(_T_NullableStringMemberName_);
            //##} else {
            result.Add(_T_RequiredStringMemberName_);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
            return result.ToHashCode();
        }

        [IgnoreMember]
        private int? _hashCode;
        /// <inheritdoc/>
        public override int GetHashCode()
        {
            if (!IsFrozen) return CalcHashCode();
            if (_hashCode.HasValue) return _hashCode.Value;
            _hashCode = CalcHashCode();
            return _hashCode.Value;
        }

    }

    [MessagePackObject]
    internal sealed class T_AbstractEntity__Default : T_AbstractEntity_, IEquatable<T_AbstractEntity__Default>
    {
        private static T_AbstractEntity__Default CreateEmpty()
        {
            var empty = new T_AbstractEntity__Default();
            empty.Freeze();
            return empty;
        }
        private static readonly T_AbstractEntity__Default _empty = CreateEmpty();
        public static new T_AbstractEntity__Default Empty => _empty;
        public T_AbstractEntity__Default() { }
        public T_AbstractEntity__Default(T_AbstractEntity_ source) : base(source) { }
        protected override IEntityBase OnPartCopy() => new T_AbstractEntity__Default(this);

        public bool Equals(T_AbstractEntity__Default? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_AbstractEntity_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
        public static bool operator ==(T_AbstractEntity__Default? left, T_AbstractEntity__Default? right) => left is not null ? left.Equals(right) : (right is null);
        public static bool operator !=(T_AbstractEntity__Default? left, T_AbstractEntity__Default? right) => left is not null ? !left.Equals(right) : (right is not null);
    }
    //##} else {
    /// <summary>
    /// Concrete class T_ConcreteEntity_
    /// </summary>
    [MessagePackObject]
    public sealed partial class T_ConcreteEntity_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_ConcreteEntity_>
    {
        //##if (false) {
        private const string T_MemberObsoleteMessage_ = null;
        private const bool T_MemberObsoleteIsError_ = false;
        private const int T_EntityId_ = 3;
        private const int KeyOffset = 10;
        private const int T_NullableCustomStructMemberKey_ = KeyOffset + 1;
        private const int T_NullableNativeStructMemberKey_ = KeyOffset + 2;
        private const int T_RequiredCustomStructMemberKey_ = KeyOffset + 3;
        private const int T_RequiredNativeStructMemberKey_ = KeyOffset + 4;
        private const int T_NullableEntityMemberKey_ = KeyOffset + 5;
        private const int T_RequiredEntityMemberKey_ = KeyOffset + 6;
        private const int T_NullableBinaryMemberKey_ = KeyOffset + 7;
        private const int T_RequiredBinaryMemberKey_ = KeyOffset + 8;
        private const int T_NullableStringMemberKey_ = KeyOffset + 9;
        private const int T_RequiredStringMemberKey_ = KeyOffset + 10;
        private const int T_MemberDefaultValue_ = 0;
        //##}

        /// <summary>
        /// Represents the unique identifier for the entity type associated with this class.
        /// </summary>
        public new const int EntityId = T_EntityId_;

        private static T_ConcreteEntity_ CreateEmpty()
        {
            var empty = new T_ConcreteEntity_();
            empty.Freeze();
            return empty;
        }
        private static readonly T_ConcreteEntity_ _empty = CreateEmpty();
        /// <summary>
        /// Gets an instance of the entity that represents an empty or default value.
        /// </summary>
        public static new T_ConcreteEntity_ Empty => _empty;

        /// <summary>
        /// Creates a new instance of the entity from the specified source, or returns the source if it is already
        /// frozen.
        /// </summary>
        public new static T_ConcreteEntity_ CreateFrom(T_ConcreteEntity_ source)
        {
            if (source.IsFrozen)
                return source;
            else
                return new T_ConcreteEntity_(source);
        }

        /// <summary>
        /// Creates a new instance of the concrete entity from the specified source entity, or returns the source if it
        /// is already a frozen concrete entity.
        /// </summary>
        public new static T_ConcreteEntity_ CreateFrom(T_IntfNameSpace_.T_EntityIntfName_ source)
        {
            if (source is T_ConcreteEntity_ concrete && concrete.IsFrozen)
                return concrete;
            else
                return new T_ConcreteEntity_(source);
        }

        /// <summary>
        /// Creates a new instance of the concrete entity by deserializing the specified buffer, if the provided entity
        /// identifier matches the expected value.
        /// </summary>
        public new static T_ConcreteEntity_ CreateFrom(int entityId, ReadOnlyMemory<byte> buffer)
        {
            if (entityId == T_ImplNameSpace_.T_ConcreteEntity_.EntityId)
                return buffer.DeserializeFromMessagePack<T_ImplNameSpace_.T_ConcreteEntity_>();
            else
                throw new ArgumentOutOfRangeException(nameof(entityId), entityId, null);
        }

        /// <inheritdoc/>
        protected override int OnGetEntityId() => T_EntityId_;

        /// <inheritdoc/>
        protected override void OnFreeze()
        {
            base.OnFreeze();
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_?.Freeze();
            //##} else {
            _T_RequiredEntityMemberName_.Freeze();
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##break;
            //##case MemberKind.String:
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        /// <inheritdoc/>
        protected override IEntityBase OnPartCopy() => new T_ConcreteEntity_(this);

        /// <summary>
        /// Initializes a new instance of the T_ConcreteEntity_ class for deserialization purposes.
        /// </summary>
        [SerializationConstructor]
        public T_ConcreteEntity_() { }

        /// <summary>
        /// Initializes a new instance of the T_ConcreteEntity_ class by copying the values from the specified source.
        /// </summary>
        public T_ConcreteEntity_(T_ConcreteEntity_ source) : base(source)
        {
            if (source is null) throw new ArgumentNullException(nameof(source));
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            _T_NullableCustomStructMemberName_ = source._T_NullableCustomStructMemberName_;
            //##} else {
            _T_NullableNativeStructMemberName_ = source._T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            _T_RequiredCustomStructMemberName_ = source._T_RequiredCustomStructMemberName_;
            //##} else {
            _T_RequiredNativeStructMemberName_ = source._T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source._T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source._T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        /// <summary>
        /// Initializes a new instance of the T_ConcreteEntity_ class by copying values from the specified source entity
        /// interface.
        /// </summary>
        public T_ConcreteEntity_(T_IntfNameSpace_.T_EntityIntfName_ source) : base(source)
        {
            if (source is null) throw new ArgumentNullException(nameof(source));
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            _T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_NullableCustomStructMemberName_);
            //##} else {
            _T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            _T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_RequiredCustomStructMemberName_);
            //##} else {
            _T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //##switch(member.Kind) {
        //##case MemberKind.Struct:
        //##if (member.IsNullable) {
        //##if (member.IsCustom) {
        [IgnoreMember]
        private T_NativeMemberType_? _T_NullableCustomStructMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableCustomStructMemberKey_)]
        public T_NativeMemberType_? Native_T_NullableCustomStructMemberName_
        {
            get => _T_NullableCustomStructMemberName_;
            set => _T_NullableCustomStructMemberName_ = IfNotFrozen(value);
        }
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [IgnoreMember]
        public T_CustomMemberType_? T_NullableCustomStructMemberName_
        {
            get => T_ConverterSpace_.T_ConverterName_.ToCustom(Native_T_NullableCustomStructMemberName_);
            set => Native_T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(value);
        }
        //##} else {
        [IgnoreMember]
        private T_NativeMemberType_? _T_NullableNativeStructMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableNativeStructMemberKey_)]
        public T_NativeMemberType_? T_NullableNativeStructMemberName_
        {
            get => _T_NullableNativeStructMemberName_;
            set => _T_NullableNativeStructMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##} else {
        //##if (member.IsCustom) {
        [IgnoreMember]
        private T_NativeMemberType_ _T_RequiredCustomStructMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredCustomStructMemberKey_)]
        public T_NativeMemberType_ Native_T_RequiredCustomStructMemberName_
        {
            get => _T_RequiredCustomStructMemberName_;
            set => _T_RequiredCustomStructMemberName_ = IfNotFrozen(value);
        }
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [IgnoreMember]
        public T_CustomMemberType_ T_RequiredCustomStructMemberName_
        {
            get => T_ConverterSpace_.T_ConverterName_.ToCustom(Native_T_RequiredCustomStructMemberName_);
            set => Native_T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(value);
        }
        //##} else {
        [IgnoreMember]
        private T_NativeMemberType_ _T_RequiredNativeStructMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredNativeStructMemberKey_)]
        public T_NativeMemberType_ T_RequiredNativeStructMemberName_
        {
            get => _T_RequiredNativeStructMemberName_;
            set => _T_RequiredNativeStructMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##}
        //##break;
        //##case MemberKind.Entity:
        //##if (member.IsNullable) {
        [IgnoreMember]
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableEntityMemberKey_)]
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_
        {
            get => _T_NullableEntityMemberName_;
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_
        {
            get => _T_NullableEntityMemberName_;
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));
        }
        //##} else {
        [IgnoreMember]
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_ _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.Empty;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredEntityMemberKey_)]
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_
        {
            get => _T_RequiredEntityMemberName_;
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_
        {
            get => _T_RequiredEntityMemberName_;
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));
        }
        //##}
        //##break;
        //##case MemberKind.Binary:
        //##if (member.IsNullable) {
        [IgnoreMember]
        private Octets? _T_NullableBinaryMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableBinaryMemberKey_)]
        public Octets? T_NullableBinaryMemberName_
        {
            get => _T_NullableBinaryMemberName_;
            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        [IgnoreMember]
        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredBinaryMemberKey_)]
        public Octets T_RequiredBinaryMemberName_
        {
            get => _T_RequiredBinaryMemberName_;
            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##case MemberKind.String:
        //##if (member.IsNullable) {
        [IgnoreMember]
        private string? _T_NullableStringMemberName_;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_NullableStringMemberKey_)]
        public string? T_NullableStringMemberName_
        {
            get => _T_NullableStringMemberName_;
            set => _T_NullableStringMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        [IgnoreMember]
        private string _T_RequiredStringMemberName_ = string.Empty;
        /// <inheritdoc/>
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [Key(T_RequiredStringMemberKey_)]
        public string T_RequiredStringMemberName_
        {
            get => _T_RequiredStringMemberName_;
            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##default:
        //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
        //##break;
        //##} // switch

        //##}

        /// <inheritdoc/>
        public bool Equals(T_ConcreteEntity_? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            if (!base.Equals(other)) return false;
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            if (_T_NullableCustomStructMemberName_ != other._T_NullableCustomStructMemberName_) return false;
            //##} else {
            if (_T_NullableNativeStructMemberName_ != other._T_NullableNativeStructMemberName_) return false;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            if (_T_RequiredCustomStructMemberName_ != other._T_RequiredCustomStructMemberName_) return false;
            //##} else {
            if (_T_RequiredNativeStructMemberName_ != other._T_RequiredNativeStructMemberName_) return false;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            if (_T_NullableEntityMemberName_ != other.T_NullableEntityMemberName_) return false;
            //##} else {
            if (_T_RequiredEntityMemberName_ != other.T_RequiredEntityMemberName_) return false;
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            if (_T_NullableBinaryMemberName_ != other._T_NullableBinaryMemberName_) return false;
            //##} else {
            if (_T_RequiredBinaryMemberName_ != other._T_RequiredBinaryMemberName_) return false;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            if (!string.Equals(_T_NullableStringMemberName_, other._T_NullableStringMemberName_)) return false;
            //##} else {
            if (!string.Equals(_T_RequiredStringMemberName_, other._T_RequiredStringMemberName_)) return false;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
            return true;
        }

        /// <inheritdoc/>
        public override bool Equals(object? obj) => obj is T_ConcreteEntity_ other && Equals(other);
        /// <inheritdoc/>
        public static bool operator ==(T_ConcreteEntity_? left, T_ConcreteEntity_? right) => left is not null ? left.Equals(right) : (right is null);
        /// <inheritdoc/>
        public static bool operator !=(T_ConcreteEntity_? left, T_ConcreteEntity_? right) => left is not null ? !left.Equals(right) : (right is not null);

        private int CalcHashCode()
        {
            HashCode result = new HashCode();
            result.Add(typeof(T_ConcreteEntity_));
            result.Add(base.GetHashCode());
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            result.Add(_T_NullableCustomStructMemberName_);
            //##} else {
            result.Add(_T_NullableNativeStructMemberName_);
            //##}
            //##} else {
            //##if (member.IsCustom) {
            result.Add(_T_RequiredCustomStructMemberName_);
            //##} else {
            result.Add(_T_RequiredNativeStructMemberName_);
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            result.Add(_T_NullableEntityMemberName_);
            //##} else {
            result.Add(_T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            result.Add(_T_NullableBinaryMemberName_);
            //##} else {
            result.Add(_T_RequiredBinaryMemberName_);
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            result.Add(_T_NullableStringMemberName_);
            //##} else {
            result.Add(_T_RequiredStringMemberName_);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
            return result.ToHashCode();
        }

        [IgnoreMember]
        private int? _hashCode;
        /// <inheritdoc/>
        public override int GetHashCode()
        {
            if (!IsFrozen) return CalcHashCode();
            if (_hashCode.HasValue) return _hashCode.Value;
            _hashCode = CalcHashCode();
            return _hashCode.Value;
        }

    }
    //##}
}
//##    }
//##}
