using System;
using System.Linq;
using DTOMaker.SrcGen.Core;
namespace DTOMaker.SrcGen.MemBlocks;
#pragma warning disable CS0162 // Unreachable code detected
public partial class EntityGenerator
{
    protected override void OnGenerate(OutputEntity entity)
    {
        using var entityScope = NewScope(entity);
        Emit("// <copyright>");
        Emit("//     Copyright (c) T_CopyrightYear_. All rights reserved by T_CopyrightOwner_.");
        Emit("// </copyright>");
        Emit("// <auto-generated>");
        Emit("//     This source file was generated by a DTOMaker source generator. Changes made to this file will be lost");
        Emit("//     if re-generated. For further information, refer to: https://github.com/datafac/dtomaker-all.");
        Emit("// </auto-generated>");
        Emit("#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required");
        Emit("#nullable enable");
        Emit("using DataFac.Memory;");
        Emit("using DTOMaker.Models;");
        Emit("using DTOMaker.Runtime;");
        Emit("using DTOMaker.Runtime.MemBlocks;");
        Emit("using DataFac.Storage;");
        Emit("using System;");
        Emit("using System.Buffers;");
        Emit("using System.IO;");
        Emit("using System.Runtime.CompilerServices;");
        Emit("using System.Runtime.InteropServices;");
        Emit("using System.Text;");
        Emit("using System.Threading;");
        Emit("using System.Threading.Tasks;");
        Emit("using T_ImplNameSpace_;");
        if (false)
        {
            Emit("#pragma warning disable CS0618 // Type or member is obsolete");
            Emit("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
            Emit("using T_CustomMemberType_ = System.DayOfWeek;");
            Emit("using T_NativeMemberType_ = System.Int32;");
            Emit("namespace DataFac.Memory");
            Emit("{");
            Emit("    public sealed class Codec_T_NativeMemberType__T_MemberBELE_ : ISpanCodec<T_NativeMemberType_>");
            Emit("    {");
            Emit("        public static T_NativeMemberType_ ReadFromSpan(ReadOnlySpan<byte> source) => Codec_Int32_LE.ReadFromSpan(source);");
            Emit("        public static void WriteToSpan(Span<byte> source, in T_NativeMemberType_ value) => Codec_Int32_LE.WriteToSpan(source, value);");
            Emit("    }");
            Emit("}");
            Emit("namespace T_MemberTypeImplSpace_");
            Emit("{");
            Emit("    public class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_, IEquatable<T_MemberTypeImplName_>");
            Emit("    {");
            Emit("        private const int ClassHeight = 1;");
            Emit("        private const int BlockOffset = 16;");
            Emit("        private const int BlockLength = 8;");
            Emit("        private const long StructureCode = 0x00_41L;");
            Emit("");
            Emit("        private static readonly EntityMetadata _metadata = new EntityMetadata(3, StructureCode);");
            Emit("");
            Emit("        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeImplName_ source)");
            Emit("        {");
            Emit("            if (source.IsFrozen) return source;");
            Emit("            return new T_MemberTypeImplName_(source);");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeImplName_? source)");
            Emit("        {");
            Emit("            return (source is null) ? null : CreateRequired(source);");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source)");
            Emit("        {");
            Emit("            if (source is T_MemberTypeImplName_ concrete && concrete.IsFrozen) return concrete;");
            Emit("            return new T_MemberTypeImplName_(source);");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? source)");
            Emit("        {");
            Emit("            return (source is null) ? null : CreateRequired(source);");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_ DeserializeFrom(ReadOnlyMemory<byte> buffer)");
            Emit("        {");
            Emit("            return new T_MemberTypeImplName_(buffer);");
            Emit("        }");
            Emit("        private readonly Memory<byte> _writableLocalBlock;");
            Emit("        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;");
            Emit("        public T_MemberTypeImplName_() : base(_metadata)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("        }");
            Emit("        public T_MemberTypeImplName_(T_MemberTypeImplName_ source) : base(_metadata, source)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("        }");
            Emit("        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) : base(_metadata, source)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            this.Field1 = source.Field1;");
            Emit("        }");
            Emit("        protected T_MemberTypeImplName_(EntityMetadata metadata, ReadOnlyMemory<byte> buffer) : base(metadata, buffer)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            _writableLocalBlock = Memory<byte>.Empty;");
            Emit("        }");
            Emit("        public T_MemberTypeImplName_(ReadOnlyMemory<byte> buffer) : this(_metadata, buffer) { }");
            Emit("");
            Emit("        protected override IEntityBase OnPartCopy() => throw new NotImplementedException();");
            Emit("        protected override int OnGetEntityId() => 3;");
            Emit("        protected override ValueTask OnPack(IDataStore dataStore, CancellationToken cancellation) => default;");
            Emit("        protected override ValueTask OnUnpack(IDataStore dataStore, int depth, CancellationToken cancellation) => default;");
            Emit("");
            Emit("        public bool Equals(T_MemberTypeImplName_? other) => base.Equals(other);");
            Emit("");
            Emit("        public Int64 Field1");
            Emit("        {");
            Emit("            get => Codec_Int64_LE.ReadFromSpan(_readonlyLocalBlock.Slice(0, 8).Span);");
            Emit("            set => Codec_Int64_LE.WriteToSpan(_writableLocalBlock.Slice(0, 8).Span, IfNotFrozen(value));");
            Emit("        }");
            Emit("    }");
            Emit("}");
            Emit("namespace T_BaseImplNameSpace_");
            Emit("{");
            Emit("    public class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>");
            Emit("    {");
            Emit("        private sealed class _EntityFactory : IMemBlocksEntityFactory<T_BaseImplName_>");
            Emit("        {");
            Emit("            public T_BaseImplName_ CreateInstance(ReadOnlyMemory<byte> buffer) => T_BaseImplName_.DeserializeFrom(buffer);");
            Emit("        }");
            Emit("        private static readonly _EntityFactory _factory = new _EntityFactory();");
            Emit("        public IMemBlocksEntityFactory<T_BaseImplName_> GetFactory() => _factory;");
            Emit("");
            Emit("        private const int T_EntityId_ = 2;");
            Emit("");
            Emit("        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0001;");
            Emit("        private const long BlockStructureCode = T_BlockStructureCode_;");
            Emit("");
            Emit("        private static readonly EntityMetadata _metadata = new EntityMetadata(T_EntityId_, BlockStructureCode);");
            Emit("");
            Emit("        private const int ClassHeight = 1;");
            Emit("        private const int BlockOffset = 16;");
            Emit("        private const int BlockLength = 4; // structure code = 0x0031L;");
            Emit("");
            Emit("        private readonly Memory<byte> _writableLocalBlock;");
            Emit("        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;");
            Emit("");
            Emit("        public new static T_BaseImplName_ DeserializeFrom(ReadOnlyMemory<byte> buffer)");
            Emit("        {");
            Emit("            var metadata = new EntityMetadata(buffer);");
            Emit("            return metadata.EntityId switch");
            Emit("            {");
            foreach (var derived in entity.DerivedEntities)
            {
                using var _ = NewScope(derived);
                Emit("                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(buffer),");
            }
            Emit("                _ => throw new InvalidDataException($\"Header contains unexpected entity id: {metadata.EntityId}\")");
            Emit("            };");
            Emit("        }");
            Emit("        public static T_BaseImplName_ CreateInstance(ReadOnlyMemory<byte> buffer) => T_BaseImplName_.DeserializeFrom(buffer);");
            Emit("");
            Emit("        protected override int OnGetEntityId() => 1;");
            Emit("        protected override void OnFreeze()");
            Emit("        {");
            Emit("            base.OnFreeze();");
            Emit("        }");
            Emit("");
            Emit("        protected override ValueTask OnPack(IDataStore dataStore, CancellationToken cancellation)");
            Emit("        {");
            Emit("            return base.OnPack(dataStore, cancellation);");
            Emit("        }");
            Emit("");
            Emit("        protected override ValueTask OnUnpack(IDataStore dataStore, int depth, CancellationToken cancellation)");
            Emit("        {");
            Emit("            return base.OnUnpack(dataStore, depth, cancellation);");
            Emit("        }");
            Emit("");
            Emit("        protected T_BaseImplName_(EntityMetadata metadata) : base(metadata)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("        }");
            Emit("");
            Emit("        protected T_BaseImplName_(EntityMetadata metadata, T_BaseImplName_ source) : base(metadata, source)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            this.BaseField1 = source.BaseField1;");
            Emit("        }");
            Emit("");
            Emit("        protected T_BaseImplName_(EntityMetadata metadata, T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(metadata, source)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            this.BaseField1 = source.BaseField1;");
            Emit("        }");
            Emit("");
            Emit("        protected T_BaseImplName_(EntityMetadata metadata, ReadOnlyMemory<byte> buffer) : base(metadata, buffer)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
            Emit("            _writableLocalBlock = Memory<byte>.Empty;");
            Emit("        }");
            Emit("");
            Emit("        public T_BaseImplName_(ReadOnlyMemory<byte> buffer) : this(_metadata, buffer) { }");
            Emit("");
            Emit("        private const int T_FieldOffset_ = 0;");
            Emit("        private const int T_FieldLength_ = 4;");
            Emit("");
            Emit("        public T_NativeMemberType_ BaseField1");
            Emit("        {");
            Emit("            get => (T_NativeMemberType_)Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span);");
            Emit("            set => Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span, IfNotFrozen(value));");
            Emit("        }");
            Emit("");
            Emit("        public bool Equals(T_BaseImplName_? other) => base.Equals(other);");
            Emit("    }");
            Emit("}");
            Emit("#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member");
        }
        Emit("namespace T_ImplNameSpace_");
        Emit("{");
        Emit("    /// <summary>");
        Emit("    /// The T_EntityImplName_ entity - the MemBlocks implementation of the T_IntfNameSpace_.T_EntityIntfName_ interface.");
        Emit("    /// </summary>");
        Emit("    public partial class T_EntityImplName_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_EntityImplName_>");
        Emit("    {");
        Emit("        private sealed class _EntityFactory : IMemBlocksEntityFactory<T_EntityImplName_>");
        Emit("        {");
        Emit("            public T_EntityImplName_ CreateInstance(ReadOnlyMemory<byte> buffer) => T_EntityImplName_.DeserializeFrom(buffer);");
        Emit("        }");
        Emit("        private static readonly _EntityFactory _factory = new _EntityFactory();");
        Emit("        /// <summary>");
        Emit("        /// Gets the factory for the T_EntityImplName_ entity.");
        Emit("        /// </summary>");
        Emit("        public IMemBlocksEntityFactory<T_EntityImplName_> GetFactory() => _factory;");
        Emit("        /// <summary>");
        Emit("        /// Creates an instance if the T_EntityImplName_ entity (or derived entity) by deserializing the buffers.");
        Emit("        /// </summary>");
        Emit("        public static T_EntityImplName_ CreateInstance(ReadOnlyMemory<byte> buffer) => T_EntityImplName_.DeserializeFrom(buffer);");
        Emit("");
        if (false)
        {
            Emit("        private const int T_ClassHeight_ = 2;");
            Emit("        private const int T_EntityId_ = 2;");
            Emit("        private const bool T_MemberObsoleteIsError_ = false;");
            Emit("        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0002;");
        }
        Emit("        private const long BlockStructureCode = T_BlockStructureCode_;");
        Emit("        private const int ClassHeight = T_ClassHeight_;");
        Emit("        private readonly Memory<byte> _writableLocalBlock;");
        Emit("        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;");
        Emit("");
        Emit("        private static readonly EntityMetadata _metadata = new EntityMetadata(T_EntityId_, BlockStructureCode);");
        Emit("");
        Emit("        private static readonly int BlockOffset = _metadata.LocalBlockOffset;");
        Emit("        private static readonly int BlockLength = _metadata.LocalBlockLength;");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a required instance of the T_EntityImplName_ entity (or derived entity) from the source.");
        Emit("        /// </summary>");
        Emit("        public new static T_EntityImplName_ CreateRequired(T_EntityImplName_ source)");
        Emit("        {");
        Emit("            if (source.IsFrozen) return source;");
        Emit("            return source switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight))
        {
            using var _ = NewScope(derived);
            Emit("                T_ImplNameSpace_.T_EntityImplName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),");
        }
        Emit("                _ => new T_ImplNameSpace_.T_EntityImplName_(source)");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates an optional instance of the T_EntityImplName_ entity (or derived entity) from the source.");
        Emit("        /// </summary>");
        Emit("        public new static T_EntityImplName_? CreateNullable(T_EntityImplName_? source)");
        Emit("        {");
        Emit("            return (source is null) ? null : CreateRequired(source);");
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a required instance of the T_EntityImplName_ entity (or derived entity) from the source.");
        Emit("        /// </summary>");
        Emit("        public new static T_EntityImplName_ CreateRequired(T_IntfNameSpace_.T_EntityIntfName_ source)");
        Emit("        {");
        Emit("            if (source is T_EntityImplName_ concrete && concrete.IsFrozen) return concrete;");
        Emit("            return source switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight))
        {
            using var _ = NewScope(derived);
            Emit("                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),");
        }
        Emit("                _ => new T_ImplNameSpace_.T_EntityImplName_(source)");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates an optional instance of the T_EntityImplName_ entity (or derived entity) from the source.");
        Emit("        /// </summary>");
        Emit("        public new static T_EntityImplName_? CreateNullable(T_IntfNameSpace_.T_EntityIntfName_? source)");
        Emit("        {");
        Emit("            return (source is null) ? null : CreateRequired(source);");
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates an instance of T_EntityImplName_ (or derived entity) by deserializing the buffer.");
        Emit("        /// </summary>");
        Emit("        public new static T_EntityImplName_ DeserializeFrom(ReadOnlyMemory<byte> buffer)");
        Emit("        {");
        Emit("            var metadata = new EntityMetadata(buffer);");
        Emit("            if (metadata.EntityId == T_EntityId_) return new T_ImplNameSpace_.T_EntityImplName_(buffer);");
        Emit("            return metadata.EntityId switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities)
        {
            using var _ = NewScope(derived);
            Emit("                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(buffer),");
        }
        Emit("                _ => throw new InvalidDataException($\"Header contains unexpected entity id: {metadata.EntityId}\")");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        /// <inheritdoc/>");
        Emit("        protected override int OnGetEntityId() => T_EntityId_;");
        Emit("        /// <inheritdoc/>");
        Emit("        protected override IEntityBase OnPartCopy() => new T_EntityImplName_(this);");
        Emit("");
        Emit("        /// <inheritdoc/>");
        Emit("        protected override void OnFreeze()");
        Emit("        {");
        Emit("            base.OnFreeze();");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_?.Freeze();");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_?.Freeze();");
                    }
                    break;
                case MemberKind.Binary:
                    break;
                case MemberKind.String:
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        /// <inheritdoc/>");
        Emit("        protected override async ValueTask OnPack(IDataStore dataStore, CancellationToken cancellation)");
        Emit("        {");
        Emit("            await base.OnPack(dataStore, cancellation);");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableEntityMemberName__Pack(dataStore, cancellation);");
                    }
                    else
                    {
                        Emit("            await T_RequiredEntityMemberName__Pack(dataStore, cancellation);");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableBinaryMemberName__Pack(dataStore, cancellation);");
                    }
                    else
                    {
                        Emit("            await T_RequiredBinaryMemberName__Pack(dataStore, cancellation);");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableStringMemberName__Pack(dataStore, cancellation);");
                    }
                    else
                    {
                        Emit("            await T_RequiredStringMemberName__Pack(dataStore, cancellation);");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        /// <inheritdoc/>");
        Emit("        protected override async ValueTask OnUnpack(IDataStore dataStore, int depth, CancellationToken cancellation)");
        Emit("        {");
        Emit("            await base.OnUnpack(dataStore, depth, cancellation);");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableEntityMemberName__Unpack(dataStore, depth, cancellation);");
                    }
                    else
                    {
                        Emit("            await T_RequiredEntityMemberName__Unpack(dataStore, depth, cancellation);");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableBinaryMemberName__Unpack(dataStore, cancellation);");
                    }
                    else
                    {
                        Emit("            await T_RequiredBinaryMemberName__Unpack(dataStore, cancellation);");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableStringMemberName__Unpack(dataStore, cancellation);");
                    }
                    else
                    {
                        Emit("            await T_RequiredStringMemberName__Unpack(dataStore, cancellation);");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        // -------------------- field map -----------------------------");
        Emit("        //  Seq.  Off.  Len.  End.  Type    Name");
        Emit("        //  ----  ----  ----  ----  ------- -------");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            Emit("        //  T_MemberSequenceR4_  T_FieldOffsetR4_  T_FieldLengthR4_  T_MemberBELE_    T_MemberTypeL7_ T_MemberName_");
            if (member.NullAddress is not null)
            {
                Emit("        //        T_BitsFieldOffsetR4_  T_NullBitPositionR4_                T_MemberName_ (isNull bit)");
            }
        }
        Emit("        // ------------------------------------------------------------");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a new instance of the T_EntityImplName_ entity.");
        Emit("        /// </summary>");
        Emit("        protected T_EntityImplName_(EntityMetadata metadata) : base(metadata)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
        Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a new instance of the T_EntityImplName_ entity.");
        Emit("        /// </summary>");
        Emit("        public T_EntityImplName_() : base(_metadata)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
        Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
        Emit("");
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a new instance of the T_EntityImplName_ entity by copying from the source instance.");
        Emit("        /// </summary>");
        Emit("        protected T_EntityImplName_(EntityMetadata metadata, T_EntityImplName_ source) : base(metadata, source)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
        Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("            this.T_NullableCustomStructMemberName_ = source.T_NullableCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            this.T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("            this.T_RequiredCustomStructMemberName_ = source.T_RequiredCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            this.T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_ = source._T_RequiredEntityMemberName_;");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a new instance of the T_EntityImplName_ entity by copying from the source instance.");
        Emit("        /// </summary>");
        Emit("        public T_EntityImplName_(T_EntityImplName_ source) : this(_metadata, source) { }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a new instance of the T_EntityImplName_ entity by copying from the source interface.");
        Emit("        /// </summary>");
        Emit("        protected T_EntityImplName_(EntityMetadata metadata, T_IntfNameSpace_.T_EntityIntfName_ source) : base(metadata, source)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
        Emit("            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("            this.T_NullableCustomStructMemberName_ = source.T_NullableCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            this.T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("            this.T_RequiredCustomStructMemberName_ = source.T_RequiredCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            this.T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(source.T_NullableEntityMemberName_);");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(source.T_RequiredEntityMemberName_);");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a new instance of the T_EntityImplName_ entity by copying from the source interface.");
        Emit("        /// </summary>");
        Emit("        public T_EntityImplName_(T_IntfNameSpace_.T_EntityIntfName_ source) : this(_metadata, source) { }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a new frozen instance of the T_EntityImplName_ entity by copying from the source.");
        Emit("        /// </summary>");
        Emit("        protected T_EntityImplName_(EntityMetadata metadata, ReadOnlyMemory<byte> buffer) : base(metadata, buffer)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
        Emit("            _writableLocalBlock = Memory<byte>.Empty;");
        Emit("        }");
        Emit("");
        Emit("        /// <summary>");
        Emit("        /// Creates a new frozen instance of the T_EntityImplName_ entity by deserializing the received buffer.");
        Emit("        /// </summary>");
        Emit("        public T_EntityImplName_(ReadOnlyMemory<byte> buffer) : base(_metadata, buffer)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);");
        Emit("            _writableLocalBlock = Memory<byte>.Empty;");
        Emit("        }");
        Emit("");
        if (false)
        {
            Emit("        private const int T_RequiredNativeStructFieldOffset_ = 0;");
            Emit("        private const int T_RequiredCustomStructFieldOffset_ = 4;");
            Emit("        private const int T_NullableCustomStructFieldOffset_ = 8;");
            Emit("        private const int T_NullableNativeStructFieldOffset_ = 12;");
            Emit("");
            Emit("        private const int T_NullableEntityFieldOffset_ = 64;");
            Emit("        private const int T_RequiredEntityFieldOffset_ = 128;");
            Emit("");
            Emit("        private const int T_NullableBinaryFieldOffset_ = 256;");
            Emit("        private const int T_RequiredBinaryFieldOffset_ = 320;");
            Emit("");
            Emit("        private const int T_NullableStringFieldOffset_ = 448;");
            Emit("        private const int T_RequiredStringFieldOffset_ = 512;");
            Emit("");
            Emit("        private const int T_FieldLength_ = 4;");
            Emit("        private const bool T_IsBigEndian_ = false;");
            Emit("        private const int T_BitsFieldOffset_ = 0;");
            Emit("        private const int T_BitsFieldLength_ = 4;");
            Emit("        private const int T_NullBitPosition_ = 0;");
        }
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        public T_CustomMemberType_? T_NullableCustomStructMemberName_");
                            Emit("        {");
                            Emit("            get");
                            Emit("            {");
                            Emit("                var bits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));");
                            Emit("                if (bits.GetBit(T_NullBitPosition_)) return null;");
                            Emit("                T_NativeMemberType_ nativeValue = Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span);");
                            Emit("                return T_ConverterSpace_.T_ConverterName_.ToCustom(nativeValue);");
                            Emit("            }");
                            Emit("            set");
                            Emit("            {");
                            Emit("                ThrowIfFrozen();");
                            Emit("                Bits32 oldBits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));");
                            Emit("                Bits32 newBits = oldBits.SetBit(T_NullBitPosition_, !value.HasValue);");
                            Emit("                if (newBits != oldBits)");
                            Emit("                {");
                            Emit("                    Codec_UInt32_LE.WriteToSpan(_writableLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span, newBits.Data);");
                            Emit("                }");
                            Emit("                if (value.HasValue)");
                            Emit("                {");
                            Emit("                    T_NativeMemberType_ nativeValue = T_ConverterSpace_.T_ConverterName_.ToNative(value.Value);");
                            Emit("                    Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span, nativeValue);");
                            Emit("                }");
                            Emit("                else");
                            Emit("                {");
                            Emit("                    _writableLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span.Clear();");
                            Emit("                }");
                            Emit("            }");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        public T_NativeMemberType_? T_NullableNativeStructMemberName_");
                            Emit("        {");
                            Emit("            get");
                            Emit("            {");
                            Emit("                var bits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));");
                            Emit("                if (bits.GetBit(T_NullBitPosition_)) return null;");
                            Emit("                return Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span);");
                            Emit("            }");
                            Emit("            set");
                            Emit("            {");
                            Emit("                ThrowIfFrozen();");
                            Emit("                Bits32 oldBits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));");
                            Emit("                Bits32 newBits = oldBits.SetBit(T_NullBitPosition_, !value.HasValue);");
                            Emit("                if (newBits != oldBits)");
                            Emit("                {");
                            Emit("                    Codec_UInt32_LE.WriteToSpan(_writableLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span, newBits.Data);");
                            Emit("                }");
                            Emit("                if (value.HasValue)");
                            Emit("                {");
                            Emit("                    Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span, value.Value);");
                            Emit("                }");
                            Emit("                else");
                            Emit("                {");
                            Emit("                    _writableLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span.Clear();");
                            Emit("                }");
                            Emit("            }");
                            Emit("        }");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        public T_CustomMemberType_ T_RequiredCustomStructMemberName_");
                            Emit("        {");
                            Emit("            get");
                            Emit("            {");
                            Emit("                T_NativeMemberType_ nativeValue = Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredCustomStructFieldOffset_, T_FieldLength_).Span);");
                            Emit("                return T_ConverterSpace_.T_ConverterName_.ToCustom(nativeValue);");
                            Emit("            }");
                            Emit("            set");
                            Emit("            {");
                            Emit("                ThrowIfFrozen();");
                            Emit("                T_NativeMemberType_ nativeValue = T_ConverterSpace_.T_ConverterName_.ToNative(value);");
                            Emit("                Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredCustomStructFieldOffset_, T_FieldLength_).Span, nativeValue);");
                            Emit("            }");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        public T_NativeMemberType_ T_RequiredNativeStructMemberName_");
                            Emit("        {");
                            Emit("            get");
                            Emit("            {");
                            Emit("                return Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredNativeStructFieldOffset_, T_FieldLength_).Span);");
                            Emit("            }");
                            Emit("            set");
                            Emit("            {");
                            Emit("                ThrowIfFrozen();");
                            Emit("                Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredNativeStructFieldOffset_, T_FieldLength_).Span, value);");
                            Emit("            }");
                            Emit("        }");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("        private async ValueTask T_NullableEntityMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var writableField = _writableLocalBlock.Slice(T_NullableEntityFieldOffset_, 64);");
                        Emit("            if (_T_NullableEntityMemberName_ is not null) await _T_NullableEntityMemberName_.Pack(dataStore, cancellation);");
                        Emit("            await PackData(_T_NullableEntityMemberName_?.Serialize(cancellation), writableField, dataStore);");
                        Emit("        }");
                        Emit("        private async ValueTask T_NullableEntityMemberName__Unpack(IDataStore dataStore, int depth, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var readonlyField = _readonlyLocalBlock.Slice(T_NullableEntityFieldOffset_, 64);");
                        Emit("            var data = await UnpackData(readonlyField, dataStore);");
                        Emit("            _T_NullableEntityMemberName_ = null;");
                        Emit("            if (data.HasValue)");
                        Emit("            {");
                        Emit("                _T_NullableEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(data.Value);");
                        Emit("                await _T_NullableEntityMemberName_.Unpack(dataStore, depth - 1, cancellation);");
                        Emit("            }");
                        Emit("        }");
                        Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;");
                        Emit("        /// <inheritdoc/>");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_NullableEntityMemberName_);");
                        Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                        Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_NullableEntityMemberName_);");
                        Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(value));");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        private async ValueTask T_RequiredEntityMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var writableField = _writableLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64);");
                        Emit("            if (_T_RequiredEntityMemberName_ is null)");
                        Emit("            {");
                        Emit("                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore, cancellation);");
                        Emit("            }");
                        Emit("            await _T_RequiredEntityMemberName_.Pack(dataStore, cancellation);");
                        Emit("            await PackData(_T_RequiredEntityMemberName_.Serialize(cancellation), writableField, dataStore);");
                        Emit("        }");
                        Emit("        private async ValueTask T_RequiredEntityMemberName__Unpack(IDataStore dataStore, int depth, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var readonlyField = _readonlyLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64);");
                        Emit("            var data = await UnpackData(readonlyField, dataStore);");
                        Emit("            if (data.HasValue)");
                        Emit("            {");
                        Emit("                _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(data.Value);");
                        Emit("                await _T_RequiredEntityMemberName_.Unpack(dataStore, depth - 1, cancellation);");
                        Emit("            }");
                        Emit("            else");
                        Emit("            {");
                        Emit("                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore, cancellation);");
                        Emit("            }");
                        Emit("        }");
                        Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_RequiredEntityMemberName_ = null;");
                        Emit("        /// <inheritdoc/>");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_");
                        Emit("        {");
                        Emit("            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));");
                        Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                        Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_");
                        Emit("        {");
                        Emit("            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));");
                        Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(value));");
                        Emit("        }");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("        private async ValueTask T_NullableBinaryMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var writableField = _writableLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64);");
                        Emit("            await PackData(_T_NullableBinaryMemberName_?.AsMemory(), writableField, dataStore);");
                        Emit("        }");
                        Emit("        private async ValueTask T_NullableBinaryMemberName__Unpack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var readonlyField = _readonlyLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64);");
                        Emit("            var data = await UnpackData(readonlyField, dataStore);");
                        Emit("            _T_NullableBinaryMemberName_ = data.HasValue ? Octets.Wrap(data.Value) : null;");
                        Emit("        }");
                        Emit("        private Octets? _T_NullableBinaryMemberName_;");
                        Emit("        /// <inheritdoc/>");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public Octets? T_NullableBinaryMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_NullableBinaryMemberName_);");
                        Emit("            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        private async ValueTask T_RequiredBinaryMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var writableField = _writableLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64);");
                        Emit("            await PackData(_T_RequiredBinaryMemberName_.AsMemory(), writableField, dataStore);");
                        Emit("        }");
                        Emit("        private async ValueTask T_RequiredBinaryMemberName__Unpack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var readonlyField = _readonlyLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64);");
                        Emit("            var data = await UnpackData(readonlyField, dataStore);");
                        Emit("            _T_RequiredBinaryMemberName_ = data.HasValue ? Octets.Wrap(data.Value) : Octets.Empty;");
                        Emit("        }");
                        Emit("        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;");
                        Emit("        /// <inheritdoc/>");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public Octets T_RequiredBinaryMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_RequiredBinaryMemberName_);");
                        Emit("            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("        private async ValueTask T_NullableStringMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var writableField = _writableLocalBlock.Slice(T_NullableStringFieldOffset_, 64);");
                        Emit("            await PackText(_T_NullableStringMemberName_, writableField, dataStore);");
                        Emit("        }");
                        Emit("        private async ValueTask T_NullableStringMemberName__Unpack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var readonlyField = _readonlyLocalBlock.Slice(T_NullableStringFieldOffset_, 64);");
                        Emit("            var data = await UnpackData(readonlyField, dataStore);");
                        Emit("#if NET8_0_OR_GREATER");
                        Emit("            _T_NullableStringMemberName_ = data.HasValue ? System.Text.Encoding.UTF8.GetString(data.Value.Span) : null;");
                        Emit("#else");
                        Emit("            _T_NullableStringMemberName_ = data.HasValue ? System.Text.Encoding.UTF8.GetString(data.Value.ToArray()) : null;");
                        Emit("#endif");
                        Emit("        }");
                        Emit("        private string? _T_NullableStringMemberName_;");
                        Emit("        /// <inheritdoc/>");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public string? T_NullableStringMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_NullableStringMemberName_);");
                        Emit("            set => _T_NullableStringMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        private async ValueTask T_RequiredStringMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var writableField = _writableLocalBlock.Slice(T_RequiredStringFieldOffset_, 64);");
                        Emit("            await PackText(_T_RequiredStringMemberName_, writableField, dataStore);");
                        Emit("        }");
                        Emit("        private async ValueTask T_RequiredStringMemberName__Unpack(IDataStore dataStore, CancellationToken cancellation)");
                        Emit("        {");
                        Emit("            var readonlyField = _readonlyLocalBlock.Slice(T_RequiredStringFieldOffset_, 64);");
                        Emit("            var data = await UnpackData(readonlyField, dataStore);");
                        Emit("#if NET8_0_OR_GREATER");
                        Emit("            _T_RequiredStringMemberName_ = data.HasValue ? System.Text.Encoding.UTF8.GetString(data.Value.Span) : string.Empty;");
                        Emit("#else");
                        Emit("            _T_RequiredStringMemberName_ = data.HasValue ? System.Text.Encoding.UTF8.GetString(data.Value.ToArray()) : string.Empty;");
                        Emit("#endif");
                        Emit("        }");
                        Emit("        private string _T_RequiredStringMemberName_ = string.Empty;");
                        Emit("        /// <inheritdoc/>");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public string T_RequiredStringMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_RequiredStringMemberName_);");
                        Emit("            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
            Emit("");
        }
        Emit("");
        Emit("        /// <inheritdoc/>");
        Emit("        public bool Equals(T_EntityImplName_? other) => base.Equals(other);");
        Emit("        /// <inheritdoc/>");
        Emit("        public override bool Equals(object? obj) => obj is T_EntityImplName_ other && Equals(other);");
        Emit("        /// <inheritdoc/>");
        Emit("        public override int GetHashCode() => base.GetHashCode();");
        Emit("        /// <inheritdoc/>");
        Emit("        public static bool operator ==(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? left.Equals(right) : (right is null);");
        Emit("        /// <inheritdoc/>");
        Emit("        public static bool operator !=(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);");
        Emit("");
        Emit("    }");
        Emit("}");
    }
}
