//##using System;
//##using System.Linq;
//##using DTOMaker.SrcGen.Core;
//##namespace DTOMaker.SrcGen.JsonSystemText;
//###pragma warning disable CS0162 // Unreachable code detected
//##public partial class EntityGenerator
//##{
//##    protected override void OnGenerate(OutputEntity entity)
//##    {
//##        using var entityScope = NewScope(entity);
// <copyright>
//     Copyright (c) T_CopyrightYear_. All rights reserved by T_CopyrightOwner_.
// </copyright>
// <auto-generated>
//     This source file was generated by a DTOMaker source generator. Changes made to this file will be lost
//     if re-generated. For further information, refer to: https://github.com/datafac/dtomaker-v2.
// </auto-generated>
#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#nullable enable
using DataFac.Memory;
using DTOMaker.Models;
using DTOMaker.Runtime.JsonSystemText;
using System;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;

//##if (false) {
using T_CustomMemberType_ = System.DayOfWeek;
using T_NativeMemberType_ = System.Int32;
namespace T_MemberTypeImplSpace_
{
    public class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_, IEquatable<T_MemberTypeImplName_>
    {
        protected override int OnGetEntityId() => 3;

        private static T_MemberTypeImplName_ CreateEmpty()
        {
            var empty = new T_MemberTypeImplName_();
            empty.Freeze();
            return empty;
        }
        private static readonly T_MemberTypeImplName_ _empty = CreateEmpty();
        public static new T_MemberTypeImplName_ Empty => _empty;

        public static T_MemberTypeImplName_ CreateFrom(T_MemberTypeImplName_ source)
        {
            if (source.IsFrozen) return source;
            return source switch
            {
                T_MemberTypeImplName_ source2 => new T_MemberTypeImplName_(source2),
                _ => throw new NotImplementedException()
            };
        }
        public static T_MemberTypeImplName_ CreateFrom(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source)
        {
            if (source is T_MemberTypeImplName_ concrete && concrete.IsFrozen) return concrete;
            return source switch
            {
                T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source2 => new T_MemberTypeImplName_(source2),
                _ => throw new NotImplementedException()
            };
        }
        public T_MemberTypeImplName_() { }
        public T_MemberTypeImplName_(T_MemberTypeImplName_ source) { }
        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) { }
        protected override IEntityBase OnShallowCopy() => throw new NotImplementedException();

        [JsonPropertyName("_f01_001")]
        public long Field1 { get; set; }

        public override int GetHashCode() => HashCode.Combine(Field1);
        public bool Equals(T_MemberTypeImplName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            if (other.Field1 != Field1) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_MemberTypeImplName_ other && Equals(other);
        public static bool operator ==(T_MemberTypeImplName_? left, T_MemberTypeImplName_? right) => left is not null ? left.Equals(right) : (right is null);
        public static bool operator !=(T_MemberTypeImplName_? left, T_MemberTypeImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);
    }
}
namespace T_BaseImplNameSpace_
{
    [JsonPolymorphic]
    [JsonDerivedType(typeof(T_ImplNameSpace_.T_EntityImplName_), 1)]
    public class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>
    {
        protected override int OnGetEntityId() => 2;

        private static T_BaseImplName_ CreateEmpty()
        {
            var empty = new T_BaseImplName_();
            empty.Freeze();
            return empty;
        }
        private static readonly T_BaseImplName_ _empty = CreateEmpty();
        public static new T_BaseImplName_ Empty => _empty;

        public T_BaseImplName_() { }
        public T_BaseImplName_(T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(source) { }
        public T_BaseImplName_(T_BaseImplName_ source) : base(source) { }

        protected override void OnFreeze() => base.OnFreeze();
        protected override IEntityBase OnShallowCopy() => throw new NotImplementedException();

        public T_NativeMemberType_ BaseField1 { get; set; }

        public bool Equals(T_BaseImplName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_BaseImplName_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
    }
}
//##}
namespace T_ImplNameSpace_
{
    //##if (entity.DerivedEntities.Count > 0) {
    [JsonPolymorphic]
    //##foreach (var derived in entity.DerivedEntities) {
    //##using var _ = NewScope(derived);
    [JsonDerivedType(typeof(T_ImplNameSpace_.T_EntityImplName_), T_EntityId_)]
    //##}
    //##}
    public partial class T_EntityImplName_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_EntityImplName_>
    {
        //##if (false) {
        private const string T_MemberObsoleteMessage_ = null;
        private const bool T_MemberObsoleteIsError_ = false;
        private const int T_MemberDefaultValue_ = 0;
        private const int T_EntityId_ = 999;
        //##}

        protected override int OnGetEntityId() => T_EntityId_;

        private static T_EntityImplName_ CreateEmpty()
        {
            var empty = new T_EntityImplName_();
            empty.Freeze();
            return empty;
        }
        private static readonly T_EntityImplName_ _empty = CreateEmpty();
        public static new T_EntityImplName_ Empty => _empty;

        public new static T_EntityImplName_ CreateFrom(T_EntityImplName_ source)
        {
            if (source.IsFrozen) return source;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_ImplNameSpace_.T_EntityImplName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(source)
            };
        }

        public new static T_EntityImplName_ CreateFrom(T_IntfNameSpace_.T_EntityIntfName_ source)
        {
            if (source is T_EntityImplName_ concrete && concrete.IsFrozen) return concrete;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(source)
            };
        }

        public new static T_EntityImplName_ CreateNewFromId(int entityId)
        {
            if (entityId == T_EntityId_) return new T_EntityImplName_();
            return entityId switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderBy(e => e.EntityId)) {
                //##using var _ = NewScope(derived);
                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(),
                //##}
                _ => throw new InvalidOperationException($"EntityId '{entityId}' is not valid.")
            };
        }

        protected override void OnFreeze()
        {
            base.OnFreeze();
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_?.Freeze();
            //##} else {
            _T_RequiredEntityMemberName_.Freeze();
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##break;
            //##case MemberKind.String:
            //##break;
            //##default:
            //##Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        protected override IEntityBase OnShallowCopy() => new T_EntityImplName_(this);

        public T_EntityImplName_() { }
        public T_EntityImplName_(T_IntfNameSpace_.T_EntityIntfName_ source) : base(source)
        {
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            _T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_NullableCustomStructMemberName_);
            //##} else {
            _T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            _T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_RequiredCustomStructMemberName_);
            //##} else {
            _T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_ is null ? null : source.T_NullableBinaryMemberName_.ToByteArray();
            //##} else {
            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_.ToByteArray();
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##} // foreach
        }
        public T_EntityImplName_(T_EntityImplName_ source) : base(source)
        {
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            _T_NullableCustomStructMemberName_ = source._T_NullableCustomStructMemberName_;
            //##} else {
            _T_NullableNativeStructMemberName_ = source._T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            _T_RequiredCustomStructMemberName_ = source._T_RequiredCustomStructMemberName_;
            //##} else {
            _T_RequiredNativeStructMemberName_ = source._T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_;
            //##} else {
            _T_RequiredEntityMemberName_ = source._T_RequiredEntityMemberName_;
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##} // foreach
        }

        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //##switch(member.Kind) {
        //##case MemberKind.Struct:
        //##if (member.IsNullable) {
        //##if (member.IsCustom) {
        [JsonPropertyName("T_NullableCustomStructMemberJsonName_")]
        [JsonInclude]
        private T_NativeMemberType_? _T_NullableCustomStructMemberName_;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonIgnore]
        public T_CustomMemberType_? T_NullableCustomStructMemberName_
        {
            get => T_ConverterSpace_.T_ConverterName_.ToCustom(_T_NullableCustomStructMemberName_);
            set => _T_NullableCustomStructMemberName_ = IfNotFrozen(T_ConverterSpace_.T_ConverterName_.ToNative(value));
        }
        //##} else {
        [JsonIgnore]
        private T_NativeMemberType_? _T_NullableNativeStructMemberName_;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonPropertyName("T_NullableNativeStructMemberJsonName_")]
        public T_NativeMemberType_? T_NullableNativeStructMemberName_
        {
            get => _T_NullableNativeStructMemberName_;
            set => _T_NullableNativeStructMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##} else {
        //##if (member.IsCustom) {
        [JsonPropertyName("T_RequiredCustomStructMemberJsonName_")]
        [JsonInclude]
        private T_NativeMemberType_ _T_RequiredCustomStructMemberName_ = T_MemberDefaultValue_;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonIgnore]
        public T_CustomMemberType_ T_RequiredCustomStructMemberName_
        {
            get => T_ConverterSpace_.T_ConverterName_.ToCustom(_T_RequiredCustomStructMemberName_);
            set => _T_RequiredCustomStructMemberName_ = IfNotFrozen(T_ConverterSpace_.T_ConverterName_.ToNative(value));
        }
        //##} else {
        [JsonIgnore]
        private T_NativeMemberType_ _T_RequiredNativeStructMemberName_ = T_MemberDefaultValue_;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonPropertyName("T_RequiredNativeStructMemberJsonName_")]
        public T_NativeMemberType_ T_RequiredNativeStructMemberName_
        {
            get => _T_RequiredNativeStructMemberName_;
            set => _T_RequiredNativeStructMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##}
        //##break;
        //##case MemberKind.Entity:
        //##if (member.IsNullable) {
        [JsonIgnore]
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonPropertyName("T_NullableEntityMemberJsonName_")]
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_
        {
            get => _T_NullableEntityMemberName_;
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);
        }
        [JsonIgnore]
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_
        {
            get => _T_NullableEntityMemberName_;
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));
        }
        //##} else {
        [JsonIgnore]
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_ _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.Empty;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonPropertyName("T_RequiredEntityMemberJsonName_")]
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_
        {
            get => _T_RequiredEntityMemberName_;
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);
        }
        [JsonIgnore]
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_
        {
            get => _T_RequiredEntityMemberName_;
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));
        }
        //##}
        //##break;
        //##case MemberKind.Binary:
        //##if (member.IsNullable) {
        [JsonPropertyName("T_NullableBinaryMemberJsonName_")]
        [JsonInclude]
        private byte[]? _T_NullableBinaryMemberName_;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonIgnore]
        public Octets? T_NullableBinaryMemberName_
        {
            get => _T_NullableBinaryMemberName_ is null ? null : _T_NullableBinaryMemberName_.Length == 0 ? Octets.Empty : new Octets(_T_NullableBinaryMemberName_);
            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value is null ? null : value.ToByteArray());
        }
        //##} else {
        [JsonPropertyName("T_RequiredBinaryMemberJsonName_")]
        [JsonInclude]
        private byte[] _T_RequiredBinaryMemberName_ = Array.Empty<byte>();
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonIgnore]
        public Octets T_RequiredBinaryMemberName_
        {
            get => _T_RequiredBinaryMemberName_.Length == 0 ? Octets.Empty : new Octets(_T_RequiredBinaryMemberName_);
            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value.ToByteArray());
        }
        //##}
        //##break;
        //##case MemberKind.String:
        //##if (member.IsNullable) {
        [JsonIgnore]
        private string? _T_NullableStringMemberName_;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonPropertyName("T_NullableStringMemberJsonName_")]
        public string? T_NullableStringMemberName_
        {
            get => _T_NullableStringMemberName_;
            set => _T_NullableStringMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        [JsonIgnore]
        private string _T_RequiredStringMemberName_ = string.Empty;
        //##if (member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        [JsonPropertyName("T_RequiredStringMemberJsonName_")]
        public string T_RequiredStringMemberName_
        {
            get => _T_RequiredStringMemberName_;
            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##default:
        //##Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
        //##break;
        //##} // switch

        //##}

        public bool Equals(T_EntityImplName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            if (_T_NullableCustomStructMemberName_ != other._T_NullableCustomStructMemberName_) return false;
            //##} else {
            if (_T_NullableNativeStructMemberName_ != other._T_NullableNativeStructMemberName_) return false;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            if (_T_RequiredCustomStructMemberName_ != other._T_RequiredCustomStructMemberName_) return false;
            //##} else {
            if (_T_RequiredNativeStructMemberName_ != other._T_RequiredNativeStructMemberName_) return false;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            if (_T_NullableEntityMemberName_ != other._T_NullableEntityMemberName_) return false;
            //##} else {
            if (_T_RequiredEntityMemberName_ != other._T_RequiredEntityMemberName_) return false;
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            if (!BinaryValuesAreEqual(_T_NullableBinaryMemberName_, other._T_NullableBinaryMemberName_)) return false;
            //##} else {
            if (!BinaryValuesAreEqual(_T_RequiredBinaryMemberName_, other._T_RequiredBinaryMemberName_)) return false;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            if (_T_NullableStringMemberName_ != other._T_NullableStringMemberName_) return false;
            //##} else {
            if (_T_RequiredStringMemberName_ != other._T_RequiredStringMemberName_) return false;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
            return true;
        }

        public override bool Equals(object? obj) => obj is T_EntityImplName_ other && Equals(other);
        public static bool operator ==(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? left.Equals(right) : (right is null);
        public static bool operator !=(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);

        private int CalcHashCode()
        {
            HashCode result = new HashCode();
            result.Add(base.GetHashCode());
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            result.Add(_T_NullableCustomStructMemberName_);
            //##} else {
            result.Add(_T_NullableNativeStructMemberName_);
            //##}
            //##} else {
            //##if (member.IsCustom) {
            result.Add(_T_RequiredCustomStructMemberName_);
            //##} else {
            result.Add(_T_RequiredNativeStructMemberName_);
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            result.Add(_T_NullableEntityMemberName_);
            //##} else {
            result.Add(_T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            if (_T_NullableBinaryMemberName_ is not null)
            {
                ReadOnlySpan<byte> span_T_NullableBinaryMemberName_ = _T_NullableBinaryMemberName_;
                result.Add(span_T_NullableBinaryMemberName_.Length);
#if NET8_0_OR_GREATER
                result.AddBytes(span_T_NullableBinaryMemberName_);
#else
                for (int i = 0; i < span_T_NullableBinaryMemberName_.Length; i++)
                {
                    result.Add(span_T_NullableBinaryMemberName_[i]);
                }
#endif
            }
            //##} else {
            ReadOnlySpan<byte> span_T_RequiredBinaryMemberName_ = _T_RequiredBinaryMemberName_;
            result.Add(span_T_RequiredBinaryMemberName_.Length);
#if NET8_0_OR_GREATER
            result.AddBytes(span_T_RequiredBinaryMemberName_);
#else
            for (int i = 0; i < span_T_RequiredBinaryMemberName_.Length; i++)
            {
                result.Add(span_T_RequiredBinaryMemberName_[i]);
            }
#endif
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            result.Add(_T_NullableStringMemberName_);
            //##} else {
            result.Add(_T_RequiredStringMemberName_);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
            return result.ToHashCode();
        }

        private int? _hashCode;
        public override int GetHashCode()
        {
            if (!IsFrozen) return CalcHashCode();
            if (_hashCode.HasValue) return _hashCode.Value;
            _hashCode = CalcHashCode();
            return _hashCode.Value;
        }

    }
}
//##    }
//##}
