using System;
using System.Linq;
using DTOMaker.SrcGen.Core;
namespace DTOMaker.SrcGen.JsonNewtonSoft;
#pragma warning disable CS0162 // Unreachable code detected
public partial class EntityGenerator
{
    protected override void OnGenerate(OutputEntity entity)
    {
        using var entityScope = NewScope(entity);
        Emit("// <copyright>");
        Emit("//     Copyright (c) T_CopyrightYear_. All rights reserved by T_CopyrightOwner_.");
        Emit("// </copyright>");
        Emit("// <auto-generated>");
        Emit("//     This source file was generated by a DTOMaker source generator. Changes made to this file will be lost");
        Emit("//     if re-generated. For further information, refer to: https://github.com/datafac/dtomaker-v2.");
        Emit("// </auto-generated>");
        Emit("#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required");
        Emit("#nullable enable");
        Emit("using DataFac.Memory;");
        Emit("using DTOMaker.Models;");
        Emit("using DTOMaker.Runtime.JsonNewtonSoft;");
        Emit("using Newtonsoft.Json;");
        Emit("using System;");
        Emit("using System.Linq;");
        Emit("using System.Runtime.CompilerServices;");
        if (false)
        {
            Emit("using T_CustomMemberType_ = System.DayOfWeek;");
            Emit("using T_NativeMemberType_ = System.Int32;");
            Emit("namespace T_MemberTypeImplSpace_");
            Emit("{");
            Emit("    public class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_, IEquatable<T_MemberTypeImplName_>");
            Emit("    {");
            Emit("        protected override int OnGetEntityId() => 3;");
            Emit("");
            Emit("        private static T_MemberTypeImplName_ CreateEmpty()");
            Emit("        {");
            Emit("            var empty = new T_MemberTypeImplName_();");
            Emit("            empty.Freeze();");
            Emit("            return empty;");
            Emit("        }");
            Emit("        private static readonly T_MemberTypeImplName_ _empty = CreateEmpty();");
            Emit("        public static new T_MemberTypeImplName_ Empty => _empty;");
            Emit("");
            Emit("        public static T_MemberTypeImplName_ CreateFrom(T_MemberTypeImplName_ source)");
            Emit("        {");
            Emit("            if (source.IsFrozen) return source;");
            Emit("            return source switch");
            Emit("            {");
            Emit("                T_MemberTypeImplName_ source2 => new T_MemberTypeImplName_(source2),");
            Emit("                _ => throw new NotImplementedException()");
            Emit("            };");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_ CreateFrom(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source)");
            Emit("        {");
            Emit("            if (source is T_MemberTypeImplName_ concrete && concrete.IsFrozen) return concrete;");
            Emit("            return source switch");
            Emit("            {");
            Emit("                T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source2 => new T_MemberTypeImplName_(source2),");
            Emit("                _ => throw new NotImplementedException()");
            Emit("            };");
            Emit("        }");
            Emit("        public T_MemberTypeImplName_() { }");
            Emit("        public T_MemberTypeImplName_(T_MemberTypeImplName_ source) { }");
            Emit("        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) { }");
            Emit("        protected override IEntityBase OnShallowCopy() => throw new NotImplementedException();");
            Emit("");
            Emit("        [JsonProperty(\"_f01_001\")]");
            Emit("        public long Field1 { get; set; }");
            Emit("");
            Emit("        public override int GetHashCode() => HashCode.Combine(Field1);");
            Emit("        public bool Equals(T_MemberTypeImplName_? other)");
            Emit("        {");
            Emit("            if (ReferenceEquals(this, other)) return true;");
            Emit("            if (other is null) return false;");
            Emit("            if (!base.Equals(other)) return false;");
            Emit("            if (other.Field1 != Field1) return false;");
            Emit("            return true;");
            Emit("        }");
            Emit("        public override bool Equals(object? obj) => obj is T_MemberTypeImplName_ other && Equals(other);");
            Emit("        public static bool operator ==(T_MemberTypeImplName_? left, T_MemberTypeImplName_? right) => left is not null ? left.Equals(right) : (right is null);");
            Emit("        public static bool operator !=(T_MemberTypeImplName_? left, T_MemberTypeImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);");
            Emit("    }");
            Emit("}");
            Emit("namespace T_BaseImplNameSpace_");
            Emit("{");
            Emit("    public class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>");
            Emit("    {");
            Emit("        protected override int OnGetEntityId() => 2;");
            Emit("");
            Emit("        private static T_BaseImplName_ CreateEmpty()");
            Emit("        {");
            Emit("            var empty = new T_BaseImplName_();");
            Emit("            empty.Freeze();");
            Emit("            return empty;");
            Emit("        }");
            Emit("        private static readonly T_BaseImplName_ _empty = CreateEmpty();");
            Emit("        public static new T_BaseImplName_ Empty => _empty;");
            Emit("");
            Emit("        public T_BaseImplName_() { }");
            Emit("        public T_BaseImplName_(T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(source) { }");
            Emit("        public T_BaseImplName_(T_BaseImplName_ source) : base(source) { }");
            Emit("");
            Emit("        protected override void OnFreeze() => base.OnFreeze();");
            Emit("        protected override IEntityBase OnShallowCopy() => throw new NotImplementedException();");
            Emit("");
            Emit("        public T_NativeMemberType_ BaseField1 { get; set; }");
            Emit("");
            Emit("        public bool Equals(T_BaseImplName_? other)");
            Emit("        {");
            Emit("            if (ReferenceEquals(this, other)) return true;");
            Emit("            if (other is null) return false;");
            Emit("            if (!base.Equals(other)) return false;");
            Emit("            return true;");
            Emit("        }");
            Emit("        public override bool Equals(object? obj) => obj is T_BaseImplName_ other && Equals(other);");
            Emit("        public override int GetHashCode() => base.GetHashCode();");
            Emit("    }");
            Emit("}");
        }
        Emit("namespace T_ImplNameSpace_");
        Emit("{");
        Emit("    public partial class T_EntityImplName_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_EntityImplName_>");
        Emit("    {");
        if (false)
        {
            Emit("        private const string T_MemberObsoleteMessage_ = null;");
            Emit("        private const bool T_MemberObsoleteIsError_ = false;");
            Emit("        private const int T_MemberDefaultValue_ = 0;");
            Emit("        private const int T_EntityId_ = 999;");
        }
        Emit("");
        Emit("        protected override int OnGetEntityId() => T_EntityId_;");
        Emit("");
        Emit("        private static T_EntityImplName_ CreateEmpty()");
        Emit("        {");
        Emit("            var empty = new T_EntityImplName_();");
        Emit("            empty.Freeze();");
        Emit("            return empty;");
        Emit("        }");
        Emit("        private static readonly T_EntityImplName_ _empty = CreateEmpty();");
        Emit("        public static new T_EntityImplName_ Empty => _empty;");
        Emit("");
        Emit("        public new static T_EntityImplName_ CreateFrom(T_EntityImplName_ source)");
        Emit("        {");
        Emit("            if (source.IsFrozen) return source;");
        Emit("            return source switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight))
        {
            using var _ = NewScope(derived);
            Emit("                T_ImplNameSpace_.T_EntityImplName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),");
        }
        Emit("                _ => new T_ImplNameSpace_.T_EntityImplName_(source)");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        public new static T_EntityImplName_ CreateFrom(T_IntfNameSpace_.T_EntityIntfName_ source)");
        Emit("        {");
        Emit("            if (source is T_EntityImplName_ concrete && concrete.IsFrozen) return concrete;");
        Emit("            return source switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight))
        {
            using var _ = NewScope(derived);
            Emit("                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),");
        }
        Emit("                _ => new T_ImplNameSpace_.T_EntityImplName_(source)");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        public new static T_EntityImplName_ CreateNewFromId(int entityId)");
        Emit("        {");
        Emit("            if (entityId == T_EntityId_) return new T_EntityImplName_();");
        Emit("            return entityId switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities.OrderBy(e => e.EntityId))
        {
            using var _ = NewScope(derived);
            Emit("                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(),");
        }
        Emit("                _ => throw new InvalidOperationException($\"EntityId '{entityId}' is not valid.\")");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        protected override void OnFreeze()");
        Emit("        {");
        Emit("            base.OnFreeze();");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_?.Freeze();");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_.Freeze();");
                    }
                    break;
                case MemberKind.Binary:
                    break;
                case MemberKind.String:
                    break;
                default:
                    Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        protected override IEntityBase OnShallowCopy() => new T_EntityImplName_(this);");
        Emit("");
        Emit("        public T_EntityImplName_()");
        Emit("        {");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_ = new T_MemberTypeImplSpace_.T_MemberTypeImplName_(); //.CreateFrom(source.T_RequiredEntityMemberName_);");
                    }
                    break;
                case MemberKind.Binary:
                    break;
                case MemberKind.String:
                    break;
                default:
                    Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        } // foreach
        Emit("        }");
        Emit("        public T_EntityImplName_(T_IntfNameSpace_.T_EntityIntfName_ source) : base(source)");
        Emit("        {");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("            _T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_NullableCustomStructMemberName_);");
                        }
                        else
                        {
                            Emit("            _T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("            _T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_RequiredCustomStructMemberName_);");
                        }
                        else
                        {
                            Emit("            _T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_NullableEntityMemberName_);");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_RequiredEntityMemberName_);");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_ is null ? null : source.T_NullableBinaryMemberName_.ToByteArray();");
                    }
                    else
                    {
                        Emit("            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_.ToByteArray();");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;");
                    }
                    break;
                default:
                    Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        } // foreach
        Emit("        }");
        Emit("        public T_EntityImplName_(T_EntityImplName_ source) : base(source)");
        Emit("        {");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("            _T_NullableCustomStructMemberName_ = source._T_NullableCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_NullableNativeStructMemberName_ = source._T_NullableNativeStructMemberName_;");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("            _T_RequiredCustomStructMemberName_ = source._T_RequiredCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredNativeStructMemberName_ = source._T_RequiredNativeStructMemberName_;");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_ = source._T_RequiredEntityMemberName_;");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;");
                    }
                    break;
                default:
                    Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        } // foreach
        Emit("        }");
        Emit("");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("        [JsonProperty(\"T_NullableCustomStructMemberJsonName_\")]");
                            Emit("        private T_NativeMemberType_? _T_NullableCustomStructMemberName_;");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [JsonIgnore]");
                            Emit("        public T_CustomMemberType_? T_NullableCustomStructMemberName_");
                            Emit("        {");
                            Emit("            get => T_ConverterSpace_.T_ConverterName_.ToCustom(_T_NullableCustomStructMemberName_);");
                            Emit("            set => _T_NullableCustomStructMemberName_ = IfNotFrozen(T_ConverterSpace_.T_ConverterName_.ToNative(value));");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        [JsonIgnore]");
                            Emit("        private T_NativeMemberType_? _T_NullableNativeStructMemberName_;");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [JsonProperty(\"T_NullableNativeStructMemberJsonName_\")]");
                            Emit("        public T_NativeMemberType_? T_NullableNativeStructMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableNativeStructMemberName_;");
                            Emit("            set => _T_NullableNativeStructMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("        [JsonProperty(\"T_RequiredCustomStructMemberJsonName_\")]");
                            Emit("        private T_NativeMemberType_ _T_RequiredCustomStructMemberName_ = T_MemberDefaultValue_;");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [JsonIgnore]");
                            Emit("        public T_CustomMemberType_ T_RequiredCustomStructMemberName_");
                            Emit("        {");
                            Emit("            get => T_ConverterSpace_.T_ConverterName_.ToCustom(_T_RequiredCustomStructMemberName_);");
                            Emit("            set => _T_RequiredCustomStructMemberName_ = IfNotFrozen(T_ConverterSpace_.T_ConverterName_.ToNative(value));");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        [JsonIgnore]");
                            Emit("        private T_NativeMemberType_ _T_RequiredNativeStructMemberName_ = T_MemberDefaultValue_;");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [JsonProperty(\"T_RequiredNativeStructMemberJsonName_\")]");
                            Emit("        public T_NativeMemberType_ T_RequiredNativeStructMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredNativeStructMemberName_;");
                            Emit("            set => _T_RequiredNativeStructMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("        [JsonIgnore]");
                        Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        [JsonProperty(\"T_NullableEntityMemberJsonName_\")]");
                        Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_");
                        Emit("        {");
                        Emit("            get => _T_NullableEntityMemberName_;");
                        Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                        Emit("        [JsonIgnore]");
                        Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_");
                        Emit("        {");
                        Emit("            get => _T_NullableEntityMemberName_;");
                        Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(value is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        [JsonIgnore]");
                        Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_ _T_RequiredEntityMemberName_; // = T_MemberTypeImplSpace_.T_MemberTypeImplName_.Empty;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        [JsonProperty(\"T_RequiredEntityMemberJsonName_\")]");
                        Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_");
                        Emit("        {");
                        Emit("            get => _T_RequiredEntityMemberName_;");
                        Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                        Emit("        [JsonIgnore]");
                        Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_");
                        Emit("        {");
                        Emit("            get => _T_RequiredEntityMemberName_;");
                        Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));");
                        Emit("        }");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("        [JsonProperty(\"T_NullableBinaryMemberJsonName_\")]");
                        Emit("        private byte[]? _T_NullableBinaryMemberName_;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        [JsonIgnore]");
                        Emit("        public Octets? T_NullableBinaryMemberName_");
                        Emit("        {");
                        Emit("            get => _T_NullableBinaryMemberName_ is null ? null : _T_NullableBinaryMemberName_.Length == 0 ? Octets.Empty : new Octets(_T_NullableBinaryMemberName_);");
                        Emit("            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value is null ? null : value.ToByteArray());");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        [JsonProperty(\"T_RequiredBinaryMemberJsonName_\")]");
                        Emit("        private byte[] _T_RequiredBinaryMemberName_ = Array.Empty<byte>();");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        [JsonIgnore]");
                        Emit("        public Octets T_RequiredBinaryMemberName_");
                        Emit("        {");
                        Emit("            get => _T_RequiredBinaryMemberName_.Length == 0 ? Octets.Empty : new Octets(_T_RequiredBinaryMemberName_);");
                        Emit("            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value.ToByteArray());");
                        Emit("        }");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("        [JsonIgnore]");
                        Emit("        private string? _T_NullableStringMemberName_;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        [JsonProperty(\"T_NullableStringMemberJsonName_\")]");
                        Emit("        public string? T_NullableStringMemberName_");
                        Emit("        {");
                        Emit("            get => _T_NullableStringMemberName_;");
                        Emit("            set => _T_NullableStringMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        [JsonIgnore]");
                        Emit("        private string _T_RequiredStringMemberName_ = string.Empty;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        [JsonProperty(\"T_RequiredStringMemberJsonName_\")]");
                        Emit("        public string T_RequiredStringMemberName_");
                        Emit("        {");
                        Emit("            get => _T_RequiredStringMemberName_;");
                        Emit("            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    break;
                default:
                    Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
            Emit("");
        }
        Emit("");
        Emit("        public bool Equals(T_EntityImplName_? other)");
        Emit("        {");
        Emit("            if (ReferenceEquals(this, other)) return true;");
        Emit("            if (other is null) return false;");
        Emit("            if (!base.Equals(other)) return false;");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("            if (_T_NullableCustomStructMemberName_ != other._T_NullableCustomStructMemberName_) return false;");
                        }
                        else
                        {
                            Emit("            if (_T_NullableNativeStructMemberName_ != other._T_NullableNativeStructMemberName_) return false;");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("            if (_T_RequiredCustomStructMemberName_ != other._T_RequiredCustomStructMemberName_) return false;");
                        }
                        else
                        {
                            Emit("            if (_T_RequiredNativeStructMemberName_ != other._T_RequiredNativeStructMemberName_) return false;");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            if (_T_NullableEntityMemberName_ != other._T_NullableEntityMemberName_) return false;");
                    }
                    else
                    {
                        Emit("            if (_T_RequiredEntityMemberName_ != other._T_RequiredEntityMemberName_) return false;");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            if (!BinaryValuesAreEqual(_T_NullableBinaryMemberName_, other._T_NullableBinaryMemberName_)) return false;");
                    }
                    else
                    {
                        Emit("            if (!BinaryValuesAreEqual(_T_RequiredBinaryMemberName_, other._T_RequiredBinaryMemberName_)) return false;");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            if (_T_NullableStringMemberName_ != other._T_NullableStringMemberName_) return false;");
                    }
                    else
                    {
                        Emit("            if (_T_RequiredStringMemberName_ != other._T_RequiredStringMemberName_) return false;");
                    }
                    break;
                default:
                    Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("            return true;");
        Emit("        }");
        Emit("");
        Emit("        public override bool Equals(object? obj) => obj is T_EntityImplName_ other && Equals(other);");
        Emit("        public static bool operator ==(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? left.Equals(right) : (right is null);");
        Emit("        public static bool operator !=(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);");
        Emit("");
        Emit("        private int CalcHashCode()");
        Emit("        {");
        Emit("            HashCode result = new HashCode();");
        Emit("            result.Add(base.GetHashCode());");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("            result.Add(_T_NullableCustomStructMemberName_);");
                        }
                        else
                        {
                            Emit("            result.Add(_T_NullableNativeStructMemberName_);");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("            result.Add(_T_RequiredCustomStructMemberName_);");
                        }
                        else
                        {
                            Emit("            result.Add(_T_RequiredNativeStructMemberName_);");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            result.Add(_T_NullableEntityMemberName_);");
                    }
                    else
                    {
                        Emit("            result.Add(_T_RequiredEntityMemberName_);");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            if (_T_NullableBinaryMemberName_ is not null)");
                        Emit("            {");
                        Emit("                ReadOnlySpan<byte> span_T_NullableBinaryMemberName_ = _T_NullableBinaryMemberName_;");
                        Emit("                result.Add(span_T_NullableBinaryMemberName_.Length);");
                        Emit("#if NET8_0_OR_GREATER");
                        Emit("                result.AddBytes(span_T_NullableBinaryMemberName_);");
                        Emit("#else");
                        Emit("                for (int i = 0; i < span_T_NullableBinaryMemberName_.Length; i++)");
                        Emit("                {");
                        Emit("                    result.Add(span_T_NullableBinaryMemberName_[i]);");
                        Emit("                }");
                        Emit("#endif");
                        Emit("            }");
                    }
                    else
                    {
                        Emit("            ReadOnlySpan<byte> span_T_RequiredBinaryMemberName_ = _T_RequiredBinaryMemberName_;");
                        Emit("            result.Add(span_T_RequiredBinaryMemberName_.Length);");
                        Emit("#if NET8_0_OR_GREATER");
                        Emit("            result.AddBytes(span_T_RequiredBinaryMemberName_);");
                        Emit("#else");
                        Emit("            for (int i = 0; i < span_T_RequiredBinaryMemberName_.Length; i++)");
                        Emit("            {");
                        Emit("                result.Add(span_T_RequiredBinaryMemberName_[i]);");
                        Emit("            }");
                        Emit("#endif");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            result.Add(_T_NullableStringMemberName_);");
                    }
                    else
                    {
                        Emit("            result.Add(_T_RequiredStringMemberName_);");
                    }
                    break;
                default:
                    Emit($"#error Implementation for {member.Name}.MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("            return result.ToHashCode();");
        Emit("        }");
        Emit("");
        Emit("        private int? _hashCode;");
        Emit("        public override int GetHashCode()");
        Emit("        {");
        Emit("            if (!IsFrozen) return CalcHashCode();");
        Emit("            if (_hashCode.HasValue) return _hashCode.Value;");
        Emit("            _hashCode = CalcHashCode();");
        Emit("            return _hashCode.Value;");
        Emit("        }");
        Emit("");
        Emit("    }");
        Emit("}");
    }
}
