using System;
using System.Linq;
using DTOMaker.SrcGen.Core;
namespace DTOMaker.SrcGen.MsgPack2;
#pragma warning disable CS0162 // Unreachable code detected
public sealed class EntityGenerator : EntityGeneratorBase
{
    public EntityGenerator(SourceGeneratorParameters parameters) : base(parameters) { }
    protected override void OnGenerate(OutputEntity entity)
    {
        using var entityScope = NewScope(entity);
        Emit("// <copyright>");
        Emit("//     Copyright (c) T_CopyrightYear_. All rights reserved by T_CopyrightOwner_.");
        Emit("// </copyright>");
        Emit("// <auto-generated>");
        Emit("//     This source file was generated by a DTOMaker source generator. Changes made to this file will be lost");
        Emit("//     if re-generated. For further information, refer to: https://github.com/datafac/dtomaker-all.");
        Emit("// </auto-generated>");
        Emit("#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required");
        Emit("#nullable enable");
        Emit("using DataFac.Memory;");
        Emit("using DTOMaker.Models;");
        Emit("using DTOMaker.Runtime.MsgPack2;");
        Emit("using MessagePack;");
        Emit("using System;");
        Emit("");
        if (false)
        {
            Emit("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
            Emit("#pragma warning disable CS0618 // Type or member is obsolete");
            Emit("using T_CustomMemberType_ = System.DayOfWeek;");
            Emit("using T_NativeMemberType_ = System.Int32;");
            Emit("namespace T_MemberTypeImplSpace_");
            Emit("{");
            Emit("    [MessagePackObject]");
            Emit("    public sealed class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_, IEquatable<T_MemberTypeImplName_>");
            Emit("    {");
            Emit("        private static readonly T_MemberTypeImplName_ _empty = new T_MemberTypeImplName_();");
            Emit("        public static T_MemberTypeImplName_ Empty => _empty;");
            Emit("");
            Emit("        public static T_MemberTypeImplName_ CreateFrom(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) => throw new NotImplementedException();");
            Emit("        protected override int OnGetEntityId() => 3;");
            Emit("        public T_MemberTypeImplName_() { }");
            Emit("        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) { }");
            Emit("        protected override IEntityBase OnPartCopy() => throw new NotImplementedException();");
            Emit("        protected override ReadOnlyMemory<byte> OnSerialize() => this.SerializeToMessagePack();");
            Emit("");
            Emit("        [Key(1)]");
            Emit("        public long Field1 { get; set; }");
            Emit("");
            Emit("        public bool Equals(T_MemberTypeImplName_? other)");
            Emit("        {");
            Emit("            if (other is null) return false;");
            Emit("            if (ReferenceEquals(this, other)) return true;");
            Emit("            if (!base.Equals(other)) return false;");
            Emit("            if (other.Field1 != Field1) return false;");
            Emit("            return true;");
            Emit("        }");
            Emit("");
            Emit("        public override bool Equals(object? obj) => obj is T_MemberTypeImplName_ other && Equals(other);");
            Emit("        public override int GetHashCode() => HashCode.Combine(Field1);");
            Emit("        public static bool operator ==(T_MemberTypeImplName_? left, T_MemberTypeImplName_? right) => left is not null ? left.Equals(right) : (right is null);");
            Emit("        public static bool operator !=(T_MemberTypeImplName_? left, T_MemberTypeImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);");
            Emit("    }");
            Emit("}");
            Emit("namespace T_BaseImplNameSpace_");
            Emit("{");
            Emit("    [MessagePackObject]");
            Emit("    [Union(T_ImplNameSpace_.T_ConcreteEntity_.EntityId, typeof(T_ImplNameSpace_.T_ConcreteEntity_))]");
            Emit("    public abstract class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>");
            Emit("    {");
            Emit("        public T_BaseImplName_() { }");
            Emit("        public T_BaseImplName_(T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(source) { }");
            Emit("        public T_BaseImplName_(T_BaseImplName_ source) : base(source) { }");
            Emit("");
            Emit("        [Key(1)] public T_NativeMemberType_ BaseField1 { get; set; }");
            Emit("");
            Emit("        public bool Equals(T_BaseImplName_? other)");
            Emit("        {");
            Emit("            if (ReferenceEquals(this, other)) return true;");
            Emit("            if (other is null) return false;");
            Emit("            if (!base.Equals(other)) return false;");
            Emit("            return true;");
            Emit("        }");
            Emit("        public override bool Equals(object? obj) => obj is T_BaseImplName_ other && Equals(other);");
            Emit("        public override int GetHashCode() => base.GetHashCode();");
            Emit("    }");
            Emit("}");
            Emit("#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member");
        }
        Emit("namespace T_ImplNameSpace_");
        Emit("{");
        if (entity.DerivedEntities.Count > 0)
        {
            Emit("    /// <summary>");
            Emit("    /// Abstract class T_AbstractEntity_");
            Emit("    /// </summary>");
            Emit("    [MessagePackObject]");
            Emit("    [Union(T_AbstractEntity_.EntityId, typeof(T_AbstractEntity__Default))]");
            foreach (var derived in entity.DerivedEntities)
            {
                using var _ = NewScope(derived);
                if (derived.DerivedEntities.Count == 0)
                {
                    Emit("    [Union(T_ConcreteEntity_.EntityId, typeof(T_ConcreteEntity_))]");
                }
            }
            Emit("    public abstract partial class T_AbstractEntity_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_AbstractEntity_>");
            Emit("    {");
            if (false)
            {
                Emit("        private const string T_MemberObsoleteMessage_ = null;");
                Emit("        private const bool T_MemberObsoleteIsError_ = false;");
                Emit("        private const int T_EntityId_ = 2;");
                Emit("        private const int KeyOffset = 10;");
                Emit("        private const int T_NullableCustomStructMemberKey_ = KeyOffset + 1;");
                Emit("        private const int T_NullableNativeStructMemberKey_ = KeyOffset + 2;");
                Emit("        private const int T_RequiredCustomStructMemberKey_ = KeyOffset + 3;");
                Emit("        private const int T_RequiredNativeStructMemberKey_ = KeyOffset + 4;");
                Emit("        private const int T_NullableEntityMemberKey_ = KeyOffset + 5;");
                Emit("        private const int T_RequiredEntityMemberKey_ = KeyOffset + 6;");
                Emit("        private const int T_NullableBinaryMemberKey_ = KeyOffset + 7;");
                Emit("        private const int T_RequiredBinaryMemberKey_ = KeyOffset + 8;");
                Emit("        private const int T_NullableStringMemberKey_ = KeyOffset + 9;");
                Emit("        private const int T_RequiredStringMemberKey_ = KeyOffset + 10;");
                Emit("        private const int T_MemberDefaultValue_ = 0;");
            }
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Represents the unique identifier for the entity type associated with this class.");
            Emit("        /// </summary>");
            Emit("        public new const int EntityId = T_EntityId_;");
            Emit("        /// <summary>");
            Emit("        /// Gets a default empty concrete entity derived from this abstract entity.");
            Emit("        /// </summary>");
            Emit("        public static new T_AbstractEntity_ Empty => T_AbstractEntity__Default.Empty;");
            Emit("        /// <summary>");
            Emit("        /// Creates a new instance of the entity from the specified source, or returns the source if it is already");
            Emit("        /// frozen.");
            Emit("        /// </summary>");
            Emit("        public new static T_ConcreteEntity_ CreateFrom(T_ConcreteEntity_ source)");
            Emit("        {");
            Emit("            if (source.IsFrozen) return source;");
            Emit("            return source switch");
            Emit("            {");
            foreach (var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight))
            {
                using var _ = NewScope(derived);
                if (derived.DerivedEntities.Count == 0)
                {
                    Emit("                T_ImplNameSpace_.T_ConcreteEntity_ source2 => new T_ImplNameSpace_.T_ConcreteEntity_(source2),");
                }
            }
            Emit("                _ => throw new ArgumentException($\"Unexpected type: {source.GetType().Name}\", nameof(source))");
            Emit("            };");
            Emit("        }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Creates a new instance of the concrete entity from the specified source entity, or returns the source if it");
            Emit("        /// is already a frozen concrete entity.");
            Emit("        /// </summary>");
            Emit("        public new static T_ConcreteEntity_ CreateFrom(T_IntfNameSpace_.T_EntityIntfName_ source)");
            Emit("        {");
            Emit("            if (source is T_ConcreteEntity_ concrete && concrete.IsFrozen) return concrete;");
            Emit("            return source switch");
            Emit("            {");
            foreach (var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight))
            {
                using var _ = NewScope(derived);
                if (derived.DerivedEntities.Count == 0)
                {
                    Emit("                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_ConcreteEntity_(source2),");
                }
            }
            Emit("                _ => throw new ArgumentException($\"Unexpected type: {source.GetType().Name}\", nameof(source))");
            Emit("            };");
            Emit("        }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Creates a new instance of the concrete entity by deserializing the specified buffer, if the provided entity");
            Emit("        /// identifier matches the expected value.");
            Emit("        /// </summary>");
            Emit("        public new static T_ConcreteEntity_ CreateFrom(int entityId, ReadOnlyMemory<byte> buffer)");
            Emit("        {");
            Emit("            return entityId switch");
            Emit("            {");
            foreach (var derived in entity.DerivedEntities)
            {
                using var _ = NewScope(derived);
                if (derived.DerivedEntities.Count == 0)
                {
                    Emit("                T_ImplNameSpace_.T_ConcreteEntity_.EntityId => buffer.DeserializeFromMessagePack<T_ImplNameSpace_.T_ConcreteEntity_>(),");
                }
            }
            Emit("                _ => throw new ArgumentOutOfRangeException(nameof(entityId), entityId, null)");
            Emit("            };");
            Emit("        }");
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        protected override int OnGetEntityId() => T_EntityId_;");
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        protected override void OnFreeze()");
            Emit("        {");
            Emit("            base.OnFreeze();");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableEntityMemberName_?.Freeze();");
                        }
                        else
                        {
                            Emit("            _T_RequiredEntityMemberName_.Freeze();");
                        }
                        break;
                    case MemberKind.Binary:
                        break;
                    case MemberKind.String:
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("        }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Initializes a new instance of the T_AbstractEntity_ class.");
            Emit("        /// </summary>");
            Emit("        protected T_AbstractEntity_() { }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Initializes a new instance of the T_AbstractEntity_ class by copying the values from the specified source.");
            Emit("        /// </summary>");
            Emit("        protected T_AbstractEntity_(T_AbstractEntity_ source) : base(source)");
            Emit("        {");
            Emit("            if (source is null) throw new ArgumentNullException(nameof(source));");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("            _T_NullableCustomStructMemberName_ = source._T_NullableCustomStructMemberName_;");
                            }
                            else
                            {
                                Emit("            _T_NullableNativeStructMemberName_ = source._T_NullableNativeStructMemberName_;");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("            _T_RequiredCustomStructMemberName_ = source._T_RequiredCustomStructMemberName_;");
                            }
                            else
                            {
                                Emit("            _T_RequiredNativeStructMemberName_ = source._T_RequiredNativeStructMemberName_;");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source._T_NullableEntityMemberName_);");
                        }
                        else
                        {
                            Emit("            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source._T_RequiredEntityMemberName_);");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("        }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Initializes a new instance of the T_AbstractEntity_ class by copying values from the specified source entity");
            Emit("        /// interface.");
            Emit("        /// </summary>");
            Emit("        public T_AbstractEntity_(T_IntfNameSpace_.T_EntityIntfName_ source) : base(source)");
            Emit("        {");
            Emit("            if (source is null) throw new ArgumentNullException(nameof(source));");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("            _T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_NullableCustomStructMemberName_);");
                            }
                            else
                            {
                                Emit("            _T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("            _T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_RequiredCustomStructMemberName_);");
                            }
                            else
                            {
                                Emit("            _T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_NullableEntityMemberName_);");
                        }
                        else
                        {
                            Emit("            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_RequiredEntityMemberName_);");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("        }");
            Emit("");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("        [IgnoreMember]");
                                Emit("        private T_NativeMemberType_? _T_NullableCustomStructMemberName_;");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [Key(T_NullableCustomStructMemberKey_)]");
                                Emit("        public T_NativeMemberType_? Native_T_NullableCustomStructMemberName_");
                                Emit("        {");
                                Emit("            get => _T_NullableCustomStructMemberName_;");
                                Emit("            set => _T_NullableCustomStructMemberName_ = IfNotFrozen(value);");
                                Emit("        }");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [IgnoreMember]");
                                Emit("        public T_CustomMemberType_? T_NullableCustomStructMemberName_");
                                Emit("        {");
                                Emit("            get => T_ConverterSpace_.T_ConverterName_.ToCustom(Native_T_NullableCustomStructMemberName_);");
                                Emit("            set => Native_T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(value);");
                                Emit("        }");
                            }
                            else
                            {
                                Emit("        [IgnoreMember]");
                                Emit("        private T_NativeMemberType_? _T_NullableNativeStructMemberName_;");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [Key(T_NullableNativeStructMemberKey_)]");
                                Emit("        public T_NativeMemberType_? T_NullableNativeStructMemberName_");
                                Emit("        {");
                                Emit("            get => _T_NullableNativeStructMemberName_;");
                                Emit("            set => _T_NullableNativeStructMemberName_ = IfNotFrozen(value);");
                                Emit("        }");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("        [IgnoreMember]");
                                Emit("        private T_NativeMemberType_ _T_RequiredCustomStructMemberName_;");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [Key(T_RequiredCustomStructMemberKey_)]");
                                Emit("        public T_NativeMemberType_ Native_T_RequiredCustomStructMemberName_");
                                Emit("        {");
                                Emit("            get => _T_RequiredCustomStructMemberName_;");
                                Emit("            set => _T_RequiredCustomStructMemberName_ = IfNotFrozen(value);");
                                Emit("        }");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [IgnoreMember]");
                                Emit("        public T_CustomMemberType_ T_RequiredCustomStructMemberName_");
                                Emit("        {");
                                Emit("            get => T_ConverterSpace_.T_ConverterName_.ToCustom(Native_T_RequiredCustomStructMemberName_);");
                                Emit("            set => Native_T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(value);");
                                Emit("        }");
                            }
                            else
                            {
                                Emit("        [IgnoreMember]");
                                Emit("        private T_NativeMemberType_ _T_RequiredNativeStructMemberName_;");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [Key(T_RequiredNativeStructMemberKey_)]");
                                Emit("        public T_NativeMemberType_ T_RequiredNativeStructMemberName_");
                                Emit("        {");
                                Emit("            get => _T_RequiredNativeStructMemberName_;");
                                Emit("            set => _T_RequiredNativeStructMemberName_ = IfNotFrozen(value);");
                                Emit("        }");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_NullableEntityMemberKey_)]");
                            Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableEntityMemberName_;");
                            Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                            Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableEntityMemberName_;");
                            Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(value is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_ _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.Empty;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_RequiredEntityMemberKey_)]");
                            Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredEntityMemberName_;");
                            Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                            Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredEntityMemberName_;");
                            Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));");
                            Emit("        }");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private Octets? _T_NullableBinaryMemberName_;");
                            if (member.IsObsolete)
                            {
                                Emit("        /// <inheritdoc/>");
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_NullableBinaryMemberKey_)]");
                            Emit("        public Octets? T_NullableBinaryMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableBinaryMemberName_;");
                            Emit("            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_RequiredBinaryMemberKey_)]");
                            Emit("        public Octets T_RequiredBinaryMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredBinaryMemberName_;");
                            Emit("            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private string? _T_NullableStringMemberName_;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_NullableStringMemberKey_)]");
                            Emit("        public string? T_NullableStringMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableStringMemberName_;");
                            Emit("            set => _T_NullableStringMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private string _T_RequiredStringMemberName_ = string.Empty;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_RequiredStringMemberKey_)]");
                            Emit("        public string T_RequiredStringMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredStringMemberName_;");
                            Emit("            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
                Emit("");
            }
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        public bool Equals(T_AbstractEntity_? other)");
            Emit("        {");
            Emit("            if (ReferenceEquals(this, other)) return true;");
            Emit("            if (other is null) return false;");
            Emit("            if (!base.Equals(other)) return false;");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("            if (_T_NullableCustomStructMemberName_ != other._T_NullableCustomStructMemberName_) return false;");
                            }
                            else
                            {
                                Emit("            if (_T_NullableNativeStructMemberName_ != other._T_NullableNativeStructMemberName_) return false;");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("            if (_T_RequiredCustomStructMemberName_ != other._T_RequiredCustomStructMemberName_) return false;");
                            }
                            else
                            {
                                Emit("            if (_T_RequiredNativeStructMemberName_ != other._T_RequiredNativeStructMemberName_) return false;");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            if (_T_NullableEntityMemberName_ != other.T_NullableEntityMemberName_) return false;");
                        }
                        else
                        {
                            Emit("            if (_T_RequiredEntityMemberName_ != other.T_RequiredEntityMemberName_) return false;");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("            if (_T_NullableBinaryMemberName_ != other._T_NullableBinaryMemberName_) return false;");
                        }
                        else
                        {
                            Emit("            if (_T_RequiredBinaryMemberName_ != other. _T_RequiredBinaryMemberName_) return false;");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("            if (!string.Equals(_T_NullableStringMemberName_, other._T_NullableStringMemberName_)) return false;");
                        }
                        else
                        {
                            Emit("            if (!string.Equals(_T_RequiredStringMemberName_, other._T_RequiredStringMemberName_)) return false;");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("            return true;");
            Emit("        }");
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        public override bool Equals(object? obj) => obj is T_AbstractEntity_ other && Equals(other);");
            Emit("        /// <inheritdoc/>");
            Emit("        public static bool operator ==(T_AbstractEntity_? left, T_AbstractEntity_? right) => left is not null ? left.Equals(right) : (right is null);");
            Emit("        /// <inheritdoc/>");
            Emit("        public static bool operator !=(T_AbstractEntity_? left, T_AbstractEntity_? right) => left is not null ? !left.Equals(right) : (right is not null);");
            Emit("");
            Emit("        private int CalcHashCode()");
            Emit("        {");
            Emit("            HashCode result = new HashCode();");
            Emit("            result.Add(typeof(T_AbstractEntity_));");
            Emit("            result.Add(base.GetHashCode());");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("            result.Add(_T_NullableCustomStructMemberName_);");
                            }
                            else
                            {
                                Emit("            result.Add(_T_NullableNativeStructMemberName_);");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("            result.Add(_T_RequiredCustomStructMemberName_);");
                            }
                            else
                            {
                                Emit("            result.Add(_T_RequiredNativeStructMemberName_);");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            result.Add(_T_NullableEntityMemberName_);");
                        }
                        else
                        {
                            Emit("            result.Add(_T_RequiredEntityMemberName_);");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("            result.Add(_T_NullableBinaryMemberName_);");
                        }
                        else
                        {
                            Emit("            result.Add(_T_RequiredBinaryMemberName_);");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("            result.Add(_T_NullableStringMemberName_);");
                        }
                        else
                        {
                            Emit("            result.Add(_T_RequiredStringMemberName_);");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("            return result.ToHashCode();");
            Emit("        }");
            Emit("");
            Emit("        [IgnoreMember]");
            Emit("        private int? _hashCode;");
            Emit("        /// <inheritdoc/>");
            Emit("        public override int GetHashCode()");
            Emit("        {");
            Emit("            if (!IsFrozen) return CalcHashCode();");
            Emit("            if (_hashCode.HasValue) return _hashCode.Value;");
            Emit("            _hashCode = CalcHashCode();");
            Emit("            return _hashCode.Value;");
            Emit("        }");
            Emit("");
            Emit("    }");
            Emit("");
            Emit("    [MessagePackObject]");
            Emit("    internal sealed class T_AbstractEntity__Default : T_AbstractEntity_, IEquatable<T_AbstractEntity__Default>");
            Emit("    {");
            Emit("        private static T_AbstractEntity__Default CreateEmpty()");
            Emit("        {");
            Emit("            var empty = new T_AbstractEntity__Default();");
            Emit("            empty.Freeze();");
            Emit("            return empty;");
            Emit("        }");
            Emit("        private static readonly T_AbstractEntity__Default _empty = CreateEmpty();");
            Emit("        public static new T_AbstractEntity__Default Empty => _empty;");
            Emit("        public T_AbstractEntity__Default() { }");
            Emit("        public T_AbstractEntity__Default(T_AbstractEntity_ source) : base(source) { }");
            Emit("        protected override IEntityBase OnPartCopy() => new T_AbstractEntity__Default(this);");
            Emit("");
            Emit("        public bool Equals(T_AbstractEntity__Default? other)");
            Emit("        {");
            Emit("            if (ReferenceEquals(this, other)) return true;");
            Emit("            if (other is null) return false;");
            Emit("            if (!base.Equals(other)) return false;");
            Emit("            return true;");
            Emit("        }");
            Emit("        public override bool Equals(object? obj) => obj is T_AbstractEntity_ other && Equals(other);");
            Emit("        public override int GetHashCode() => base.GetHashCode();");
            Emit("        public static bool operator ==(T_AbstractEntity__Default? left, T_AbstractEntity__Default? right) => left is not null ? left.Equals(right) : (right is null);");
            Emit("        public static bool operator !=(T_AbstractEntity__Default? left, T_AbstractEntity__Default? right) => left is not null ? !left.Equals(right) : (right is not null);");
            Emit("    }");
        }
        else
        {
            Emit("    /// <summary>");
            Emit("    /// Concrete class T_ConcreteEntity_");
            Emit("    /// </summary>");
            Emit("    [MessagePackObject]");
            Emit("    public sealed partial class T_ConcreteEntity_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_ConcreteEntity_>");
            Emit("    {");
            if (false)
            {
                Emit("        private const string T_MemberObsoleteMessage_ = null;");
                Emit("        private const bool T_MemberObsoleteIsError_ = false;");
                Emit("        private const int T_EntityId_ = 3;");
                Emit("        private const int KeyOffset = 10;");
                Emit("        private const int T_NullableCustomStructMemberKey_ = KeyOffset + 1;");
                Emit("        private const int T_NullableNativeStructMemberKey_ = KeyOffset + 2;");
                Emit("        private const int T_RequiredCustomStructMemberKey_ = KeyOffset + 3;");
                Emit("        private const int T_RequiredNativeStructMemberKey_ = KeyOffset + 4;");
                Emit("        private const int T_NullableEntityMemberKey_ = KeyOffset + 5;");
                Emit("        private const int T_RequiredEntityMemberKey_ = KeyOffset + 6;");
                Emit("        private const int T_NullableBinaryMemberKey_ = KeyOffset + 7;");
                Emit("        private const int T_RequiredBinaryMemberKey_ = KeyOffset + 8;");
                Emit("        private const int T_NullableStringMemberKey_ = KeyOffset + 9;");
                Emit("        private const int T_RequiredStringMemberKey_ = KeyOffset + 10;");
                Emit("        private const int T_MemberDefaultValue_ = 0;");
            }
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Represents the unique identifier for the entity type associated with this class.");
            Emit("        /// </summary>");
            Emit("        public new const int EntityId = T_EntityId_;");
            Emit("");
            Emit("        private static T_ConcreteEntity_ CreateEmpty()");
            Emit("        {");
            Emit("            var empty = new T_ConcreteEntity_();");
            Emit("            empty.Freeze();");
            Emit("            return empty;");
            Emit("        }");
            Emit("        private static readonly T_ConcreteEntity_ _empty = CreateEmpty();");
            Emit("        /// <summary>");
            Emit("        /// Gets an instance of the entity that represents an empty or default value.");
            Emit("        /// </summary>");
            Emit("        public static new T_ConcreteEntity_ Empty => _empty;");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Creates a new instance of the entity from the specified source, or returns the source if it is already");
            Emit("        /// frozen.");
            Emit("        /// </summary>");
            Emit("        public new static T_ConcreteEntity_ CreateFrom(T_ConcreteEntity_ source)");
            Emit("        {");
            Emit("            if (source.IsFrozen)");
            Emit("                return source;");
            Emit("            else");
            Emit("                return new T_ConcreteEntity_(source);");
            Emit("        }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Creates a new instance of the concrete entity from the specified source entity, or returns the source if it");
            Emit("        /// is already a frozen concrete entity.");
            Emit("        /// </summary>");
            Emit("        public new static T_ConcreteEntity_ CreateFrom(T_IntfNameSpace_.T_EntityIntfName_ source)");
            Emit("        {");
            Emit("            if (source is T_ConcreteEntity_ concrete && concrete.IsFrozen)");
            Emit("                return concrete;");
            Emit("            else");
            Emit("                return new T_ConcreteEntity_(source);");
            Emit("        }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Creates a new instance of the concrete entity by deserializing the specified buffer, if the provided entity");
            Emit("        /// identifier matches the expected value.");
            Emit("        /// </summary>");
            Emit("        public new static T_ConcreteEntity_ CreateFrom(int entityId, ReadOnlyMemory<byte> buffer)");
            Emit("        {");
            Emit("            if (entityId == T_ImplNameSpace_.T_ConcreteEntity_.EntityId)");
            Emit("                return buffer.DeserializeFromMessagePack<T_ImplNameSpace_.T_ConcreteEntity_>();");
            Emit("            else");
            Emit("                throw new ArgumentOutOfRangeException(nameof(entityId), entityId, null);");
            Emit("        }");
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        protected override int OnGetEntityId() => T_EntityId_;");
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        protected override void OnFreeze()");
            Emit("        {");
            Emit("            base.OnFreeze();");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableEntityMemberName_?.Freeze();");
                        }
                        else
                        {
                            Emit("            _T_RequiredEntityMemberName_.Freeze();");
                        }
                        break;
                    case MemberKind.Binary:
                        break;
                    case MemberKind.String:
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("        }");
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        protected override ReadOnlyMemory<byte> OnSerialize() => this.SerializeToMessagePack();");
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        protected override IEntityBase OnPartCopy() => new T_ConcreteEntity_(this);");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Initializes a new instance of the T_ConcreteEntity_ class for deserialization purposes.");
            Emit("        /// </summary>");
            Emit("        [SerializationConstructor]");
            Emit("        public T_ConcreteEntity_() { }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Initializes a new instance of the T_ConcreteEntity_ class by copying the values from the specified source.");
            Emit("        /// </summary>");
            Emit("        public T_ConcreteEntity_(T_ConcreteEntity_ source) : base(source)");
            Emit("        {");
            Emit("            if (source is null) throw new ArgumentNullException(nameof(source));");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("            _T_NullableCustomStructMemberName_ = source._T_NullableCustomStructMemberName_;");
                            }
                            else
                            {
                                Emit("            _T_NullableNativeStructMemberName_ = source._T_NullableNativeStructMemberName_;");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("            _T_RequiredCustomStructMemberName_ = source._T_RequiredCustomStructMemberName_;");
                            }
                            else
                            {
                                Emit("            _T_RequiredNativeStructMemberName_ = source._T_RequiredNativeStructMemberName_;");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source._T_NullableEntityMemberName_);");
                        }
                        else
                        {
                            Emit("            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source._T_RequiredEntityMemberName_);");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("        }");
            Emit("");
            Emit("        /// <summary>");
            Emit("        /// Initializes a new instance of the T_ConcreteEntity_ class by copying values from the specified source entity");
            Emit("        /// interface.");
            Emit("        /// </summary>");
            Emit("        public T_ConcreteEntity_(T_IntfNameSpace_.T_EntityIntfName_ source) : base(source)");
            Emit("        {");
            Emit("            if (source is null) throw new ArgumentNullException(nameof(source));");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("            _T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_NullableCustomStructMemberName_);");
                            }
                            else
                            {
                                Emit("            _T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("            _T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(source.T_RequiredCustomStructMemberName_);");
                            }
                            else
                            {
                                Emit("            _T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_NullableEntityMemberName_);");
                        }
                        else
                        {
                            Emit("            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(source.T_RequiredEntityMemberName_);");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;");
                        }
                        else
                        {
                            Emit("            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("        }");
            Emit("");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("        [IgnoreMember]");
                                Emit("        private T_NativeMemberType_? _T_NullableCustomStructMemberName_;");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [Key(T_NullableCustomStructMemberKey_)]");
                                Emit("        public T_NativeMemberType_? Native_T_NullableCustomStructMemberName_");
                                Emit("        {");
                                Emit("            get => _T_NullableCustomStructMemberName_;");
                                Emit("            set => _T_NullableCustomStructMemberName_ = IfNotFrozen(value);");
                                Emit("        }");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [IgnoreMember]");
                                Emit("        public T_CustomMemberType_? T_NullableCustomStructMemberName_");
                                Emit("        {");
                                Emit("            get => T_ConverterSpace_.T_ConverterName_.ToCustom(Native_T_NullableCustomStructMemberName_);");
                                Emit("            set => Native_T_NullableCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(value);");
                                Emit("        }");
                            }
                            else
                            {
                                Emit("        [IgnoreMember]");
                                Emit("        private T_NativeMemberType_? _T_NullableNativeStructMemberName_;");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [Key(T_NullableNativeStructMemberKey_)]");
                                Emit("        public T_NativeMemberType_? T_NullableNativeStructMemberName_");
                                Emit("        {");
                                Emit("            get => _T_NullableNativeStructMemberName_;");
                                Emit("            set => _T_NullableNativeStructMemberName_ = IfNotFrozen(value);");
                                Emit("        }");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("        [IgnoreMember]");
                                Emit("        private T_NativeMemberType_ _T_RequiredCustomStructMemberName_;");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [Key(T_RequiredCustomStructMemberKey_)]");
                                Emit("        public T_NativeMemberType_ Native_T_RequiredCustomStructMemberName_");
                                Emit("        {");
                                Emit("            get => _T_RequiredCustomStructMemberName_;");
                                Emit("            set => _T_RequiredCustomStructMemberName_ = IfNotFrozen(value);");
                                Emit("        }");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [IgnoreMember]");
                                Emit("        public T_CustomMemberType_ T_RequiredCustomStructMemberName_");
                                Emit("        {");
                                Emit("            get => T_ConverterSpace_.T_ConverterName_.ToCustom(Native_T_RequiredCustomStructMemberName_);");
                                Emit("            set => Native_T_RequiredCustomStructMemberName_ = T_ConverterSpace_.T_ConverterName_.ToNative(value);");
                                Emit("        }");
                            }
                            else
                            {
                                Emit("        [IgnoreMember]");
                                Emit("        private T_NativeMemberType_ _T_RequiredNativeStructMemberName_;");
                                Emit("        /// <inheritdoc/>");
                                if (member.IsObsolete)
                                {
                                    Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                                }
                                Emit("        [Key(T_RequiredNativeStructMemberKey_)]");
                                Emit("        public T_NativeMemberType_ T_RequiredNativeStructMemberName_");
                                Emit("        {");
                                Emit("            get => _T_RequiredNativeStructMemberName_;");
                                Emit("            set => _T_RequiredNativeStructMemberName_ = IfNotFrozen(value);");
                                Emit("        }");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_NullableEntityMemberKey_)]");
                            Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableEntityMemberName_;");
                            Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                            Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableEntityMemberName_;");
                            Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(value is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_ _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.Empty;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_RequiredEntityMemberKey_)]");
                            Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredEntityMemberName_;");
                            Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                            Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredEntityMemberName_;");
                            Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateFrom(value));");
                            Emit("        }");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private Octets? _T_NullableBinaryMemberName_;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_NullableBinaryMemberKey_)]");
                            Emit("        public Octets? T_NullableBinaryMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableBinaryMemberName_;");
                            Emit("            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_RequiredBinaryMemberKey_)]");
                            Emit("        public Octets T_RequiredBinaryMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredBinaryMemberName_;");
                            Emit("            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private string? _T_NullableStringMemberName_;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_NullableStringMemberKey_)]");
                            Emit("        public string? T_NullableStringMemberName_");
                            Emit("        {");
                            Emit("            get => _T_NullableStringMemberName_;");
                            Emit("            set => _T_NullableStringMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                        else
                        {
                            Emit("        [IgnoreMember]");
                            Emit("        private string _T_RequiredStringMemberName_ = string.Empty;");
                            Emit("        /// <inheritdoc/>");
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        [Key(T_RequiredStringMemberKey_)]");
                            Emit("        public string T_RequiredStringMemberName_");
                            Emit("        {");
                            Emit("            get => _T_RequiredStringMemberName_;");
                            Emit("            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);");
                            Emit("        }");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
                Emit("");
            }
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        public bool Equals(T_ConcreteEntity_? other)");
            Emit("        {");
            Emit("            if (other is null) return false;");
            Emit("            if (ReferenceEquals(this, other)) return true;");
            Emit("            if (!base.Equals(other)) return false;");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("            if (_T_NullableCustomStructMemberName_ != other._T_NullableCustomStructMemberName_) return false;");
                            }
                            else
                            {
                                Emit("            if (_T_NullableNativeStructMemberName_ != other._T_NullableNativeStructMemberName_) return false;");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("            if (_T_RequiredCustomStructMemberName_ != other._T_RequiredCustomStructMemberName_) return false;");
                            }
                            else
                            {
                                Emit("            if (_T_RequiredNativeStructMemberName_ != other._T_RequiredNativeStructMemberName_) return false;");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            if (_T_NullableEntityMemberName_ != other.T_NullableEntityMemberName_) return false;");
                        }
                        else
                        {
                            Emit("            if (_T_RequiredEntityMemberName_ != other.T_RequiredEntityMemberName_) return false;");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("            if (_T_NullableBinaryMemberName_ != other._T_NullableBinaryMemberName_) return false;");
                        }
                        else
                        {
                            Emit("            if (_T_RequiredBinaryMemberName_ != other._T_RequiredBinaryMemberName_) return false;");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("            if (!string.Equals(_T_NullableStringMemberName_, other._T_NullableStringMemberName_)) return false;");
                        }
                        else
                        {
                            Emit("            if (!string.Equals(_T_RequiredStringMemberName_, other._T_RequiredStringMemberName_)) return false;");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("            return true;");
            Emit("        }");
            Emit("");
            Emit("        /// <inheritdoc/>");
            Emit("        public override bool Equals(object? obj) => obj is T_ConcreteEntity_ other && Equals(other);");
            Emit("        /// <inheritdoc/>");
            Emit("        public static bool operator ==(T_ConcreteEntity_? left, T_ConcreteEntity_? right) => left is not null ? left.Equals(right) : (right is null);");
            Emit("        /// <inheritdoc/>");
            Emit("        public static bool operator !=(T_ConcreteEntity_? left, T_ConcreteEntity_? right) => left is not null ? !left.Equals(right) : (right is not null);");
            Emit("");
            Emit("        private int CalcHashCode()");
            Emit("        {");
            Emit("            HashCode result = new HashCode();");
            Emit("            result.Add(typeof(T_ConcreteEntity_));");
            Emit("            result.Add(base.GetHashCode());");
            foreach (var member in entity.Members)
            {
                using var _ = NewScope(entity, member);
                switch (member.Kind)
                {
                    case MemberKind.Struct:
                        if (member.IsNullable)
                        {
                            if (member.IsCustom)
                            {
                                Emit("            result.Add(_T_NullableCustomStructMemberName_);");
                            }
                            else
                            {
                                Emit("            result.Add(_T_NullableNativeStructMemberName_);");
                            }
                        }
                        else
                        {
                            if (member.IsCustom)
                            {
                                Emit("            result.Add(_T_RequiredCustomStructMemberName_);");
                            }
                            else
                            {
                                Emit("            result.Add(_T_RequiredNativeStructMemberName_);");
                            }
                        }
                        break;
                    case MemberKind.Entity:
                        if (member.IsNullable)
                        {
                            Emit("            result.Add(_T_NullableEntityMemberName_);");
                        }
                        else
                        {
                            Emit("            result.Add(_T_RequiredEntityMemberName_);");
                        }
                        break;
                    case MemberKind.Binary:
                        if (member.IsNullable)
                        {
                            Emit("            result.Add(_T_NullableBinaryMemberName_);");
                        }
                        else
                        {
                            Emit("            result.Add(_T_RequiredBinaryMemberName_);");
                        }
                        break;
                    case MemberKind.String:
                        if (member.IsNullable)
                        {
                            Emit("            result.Add(_T_NullableStringMemberName_);");
                        }
                        else
                        {
                            Emit("            result.Add(_T_RequiredStringMemberName_);");
                        }
                        break;
                    default:
                        Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                        break;
                } // switch
            }
            Emit("            return result.ToHashCode();");
            Emit("        }");
            Emit("");
            Emit("        [IgnoreMember]");
            Emit("        private int? _hashCode;");
            Emit("        /// <inheritdoc/>");
            Emit("        public override int GetHashCode()");
            Emit("        {");
            Emit("            if (!IsFrozen) return CalcHashCode();");
            Emit("            if (_hashCode.HasValue) return _hashCode.Value;");
            Emit("            _hashCode = CalcHashCode();");
            Emit("            return _hashCode.Value;");
            Emit("        }");
            Emit("");
            Emit("    }");
        }
        Emit("}");
    }
}
