//##using System;
//##using System.Linq;
//##using DTOMaker.SrcGen.Core;
//##namespace DTOMaker.SrcGen.MemBlocks;
//###pragma warning disable CS0162 // Unreachable code detected
//##public partial class EntityGenerator
//##{
//##    protected override void OnGenerate(OutputEntity entity)
//##    {
//##        using var entityScope = NewScope(entity);
// <copyright>
//     Copyright (c) T_CopyrightYear_. All rights reserved by T_CopyrightOwner_.
// </copyright>
// <auto-generated>
//     This source file was generated by a DTOMaker source generator. Changes made to this file will be lost
//     if re-generated. For further information, refer to: https://github.com/datafac/dtomaker-v2.
// </auto-generated>
#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#nullable enable
using DataFac.Memory;
using DTOMaker.Models;
using DTOMaker.Runtime;
using DTOMaker.Runtime.MemBlocks;
using DataFac.Storage;
using System;
using System.Buffers;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using T_ImplNameSpace_;
//##if(false) {
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using T_CustomMemberType_ = System.DayOfWeek;
using T_NativeMemberType_ = System.Int32;
namespace DataFac.Memory
{
    public sealed class Codec_T_NativeMemberType__T_MemberBELE_ : ISpanCodec<T_NativeMemberType_>
    {
        public static T_NativeMemberType_ ReadFromSpan(ReadOnlySpan<byte> source) => Codec_Int32_LE.ReadFromSpan(source);
        public static void WriteToSpan(Span<byte> source, in T_NativeMemberType_ value) => Codec_Int32_LE.WriteToSpan(source, value);
    }
}
namespace T_MemberTypeImplSpace_
{
    public class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_, IEquatable<T_MemberTypeImplName_>
    {
        private const int ClassHeight = 1;
        private const int BlockOffset = 16;
        private const int BlockLength = 8;
        private const long StructureCode = 0x00_41L;

        private static readonly EntityMetadata _metadata = new EntityMetadata(3, StructureCode);

        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeImplName_ source)
        {
            if (source.IsFrozen) return source;
            return new T_MemberTypeImplName_(source);
        }
        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeImplName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }
        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source)
        {
            if (source is T_MemberTypeImplName_ concrete && concrete.IsFrozen) return concrete;
            return new T_MemberTypeImplName_(source);
        }
        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }
        public static T_MemberTypeImplName_ DeserializeFrom(ReadOnlyMemory<byte> buffer)
        {
            return new T_MemberTypeImplName_(buffer);
        }
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;
        public T_MemberTypeImplName_() : base(_metadata)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
        }
        public T_MemberTypeImplName_(T_MemberTypeImplName_ source) : base(_metadata, source)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
        }
        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) : base(_metadata, source)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
            this.Field1 = source.Field1;
        }
        protected T_MemberTypeImplName_(EntityMetadata metadata, ReadOnlyMemory<byte> buffer) : base(metadata, buffer)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = Memory<byte>.Empty;
        }
        public T_MemberTypeImplName_(ReadOnlyMemory<byte> buffer) : this(_metadata, buffer) { }

        protected override IEntityBase OnShallowCopy() => throw new NotImplementedException();
        protected override int OnGetEntityId() => 3;
        protected override ValueTask OnPack(IDataStore dataStore, CancellationToken cancellation) => default;
        protected override ValueTask OnUnpack(IDataStore dataStore, int depth, CancellationToken cancellation) => default;

        public bool Equals(T_MemberTypeImplName_? other) => base.Equals(other);

        public Int64 Field1
        {
            get => Codec_Int64_LE.ReadFromSpan(_readonlyLocalBlock.Slice(0, 8).Span);
            set => Codec_Int64_LE.WriteToSpan(_writableLocalBlock.Slice(0, 8).Span, IfNotFrozen(value));
        }
    }
}
namespace T_BaseImplNameSpace_
{
    public class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>
    {
        private sealed class _EntityFactory : IMemBlocksEntityFactory<T_BaseImplName_>
        {
            public T_BaseImplName_ CreateInstance(ReadOnlyMemory<byte> buffer) => T_BaseImplName_.DeserializeFrom(buffer);
        }
        private static readonly _EntityFactory _factory = new _EntityFactory();
        public IMemBlocksEntityFactory<T_BaseImplName_> GetFactory() => _factory;

        private const int T_EntityId_ = 2;

        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0001;
        private const long BlockStructureCode = T_BlockStructureCode_;

        private static readonly EntityMetadata _metadata = new EntityMetadata(T_EntityId_, BlockStructureCode);

        private const int ClassHeight = 1;
        private const int BlockOffset = 16;
        private const int BlockLength = 4; // structure code = 0x0031L;

        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;

        public new static T_BaseImplName_ DeserializeFrom(ReadOnlyMemory<byte> buffer)
        {
            var metadata = new EntityMetadata(buffer);
            return metadata.EntityId switch
            {
                //##foreach(var derived in entity.DerivedEntities) {
                //##using var _ = NewScope(derived);
                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(buffer),
                //##}
                _ => throw new InvalidDataException($"Header contains unexpected entity id: {metadata.EntityId}")
            };
        }
        public static T_BaseImplName_ CreateInstance(ReadOnlyMemory<byte> buffer) => T_BaseImplName_.DeserializeFrom(buffer);

        protected override int OnGetEntityId() => 1;
        protected override void OnFreeze()
        {
            base.OnFreeze();
        }

        protected override ValueTask OnPack(IDataStore dataStore, CancellationToken cancellation)
        {
            return base.OnPack(dataStore, cancellation);
        }

        protected override ValueTask OnUnpack(IDataStore dataStore, int depth, CancellationToken cancellation)
        {
            return base.OnUnpack(dataStore, depth, cancellation);
        }

        protected T_BaseImplName_(EntityMetadata metadata) : base(metadata)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
        }

        protected T_BaseImplName_(EntityMetadata metadata, T_BaseImplName_ source) : base(metadata, source)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
            this.BaseField1 = source.BaseField1;
        }

        protected T_BaseImplName_(EntityMetadata metadata, T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(metadata, source)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
            this.BaseField1 = source.BaseField1;
        }

        protected T_BaseImplName_(EntityMetadata metadata, ReadOnlyMemory<byte> buffer) : base(metadata, buffer)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = Memory<byte>.Empty;
        }

        public T_BaseImplName_(ReadOnlyMemory<byte> buffer) : this(_metadata, buffer) { }

        private const int T_FieldOffset_ = 0;
        private const int T_FieldLength_ = 4;

        public T_NativeMemberType_ BaseField1
        {
            get => (T_NativeMemberType_)Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span);
            set => Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span, IfNotFrozen(value));
        }

        public bool Equals(T_BaseImplName_? other) => base.Equals(other);
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
//##}
namespace T_ImplNameSpace_
{
    /// <summary>
    /// The T_EntityImplName_ entity - the MemBlocks implementation of the T_IntfNameSpace_.T_EntityIntfName_ interface.
    /// </summary>
    public partial class T_EntityImplName_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_EntityImplName_>
    {
        private sealed class _EntityFactory : IMemBlocksEntityFactory<T_EntityImplName_>
        {
            public T_EntityImplName_ CreateInstance(ReadOnlyMemory<byte> buffer) => T_EntityImplName_.DeserializeFrom(buffer);
        }
        private static readonly _EntityFactory _factory = new _EntityFactory();
        /// <summary>
        /// Gets the factory for the T_EntityImplName_ entity.
        /// </summary>
        public IMemBlocksEntityFactory<T_EntityImplName_> GetFactory() => _factory;
        /// <summary>
        /// Creates an instance if the T_EntityImplName_ entity (or derived entity) by deserializing the buffers.
        /// </summary>
        public static T_EntityImplName_ CreateInstance(ReadOnlyMemory<byte> buffer) => T_EntityImplName_.DeserializeFrom(buffer);

        //##if(false) {
        private const int T_ClassHeight_ = 2;
        private const int T_EntityId_ = 2;
        private const bool T_MemberObsoleteIsError_ = false;
        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0002;
        //##}
        private const long BlockStructureCode = T_BlockStructureCode_;
        private const int ClassHeight = T_ClassHeight_;
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;

        private static readonly EntityMetadata _metadata = new EntityMetadata(T_EntityId_, BlockStructureCode);

        private static readonly int BlockOffset = _metadata.LocalBlockOffset;
        private static readonly int BlockLength = _metadata.LocalBlockLength;

        /// <summary>
        /// Creates a required instance of the T_EntityImplName_ entity (or derived entity) from the source.
        /// </summary>
        public new static T_EntityImplName_ CreateRequired(T_EntityImplName_ source)
        {
            if (source.IsFrozen) return source;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_ImplNameSpace_.T_EntityImplName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(source)
            };
        }

        /// <summary>
        /// Creates an optional instance of the T_EntityImplName_ entity (or derived entity) from the source.
        /// </summary>
        public new static T_EntityImplName_? CreateNullable(T_EntityImplName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }

        /// <summary>
        /// Creates a required instance of the T_EntityImplName_ entity (or derived entity) from the source.
        /// </summary>
        public new static T_EntityImplName_ CreateRequired(T_IntfNameSpace_.T_EntityIntfName_ source)
        {
            if (source is T_EntityImplName_ concrete && concrete.IsFrozen) return concrete;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(source)
            };
        }

        /// <summary>
        /// Creates an optional instance of the T_EntityImplName_ entity (or derived entity) from the source.
        /// </summary>
        public new static T_EntityImplName_? CreateNullable(T_IntfNameSpace_.T_EntityIntfName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }

        /// <summary>
        /// Creates an instance of T_EntityImplName_ (or derived entity) by deserializing the buffer.
        /// </summary>
        public new static T_EntityImplName_ DeserializeFrom(ReadOnlyMemory<byte> buffer)
        {
            var metadata = new EntityMetadata(buffer);
            if (metadata.EntityId == T_EntityId_) return new T_ImplNameSpace_.T_EntityImplName_(buffer);
            return metadata.EntityId switch
            {
                //##foreach(var derived in entity.DerivedEntities) {
                //##using var _ = NewScope(derived);
                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(buffer),
                //##}
                _ => throw new InvalidDataException($"Header contains unexpected entity id: {metadata.EntityId}")
            };
        }

        /// <inheritdoc/>
        protected override int OnGetEntityId() => T_EntityId_;
        /// <inheritdoc/>
        protected override IEntityBase OnShallowCopy() => new T_EntityImplName_(this);

        /// <inheritdoc/>
        protected override void OnFreeze()
        {
            base.OnFreeze();
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_?.Freeze();
            //##} else {
            _T_RequiredEntityMemberName_?.Freeze();
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##break;
            //##case MemberKind.String:
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        /// <inheritdoc/>
        protected override async ValueTask OnPack(IDataStore dataStore, CancellationToken cancellation)
        {
            await base.OnPack(dataStore, cancellation);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            await T_NullableEntityMemberName__Pack(dataStore, cancellation);
            //##} else {
            await T_RequiredEntityMemberName__Pack(dataStore, cancellation);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            await T_NullableBinaryMemberName__Pack(dataStore, cancellation);
            //##} else {
            await T_RequiredBinaryMemberName__Pack(dataStore, cancellation);
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            await T_NullableStringMemberName__Pack(dataStore, cancellation);
            //##} else {
            await T_RequiredStringMemberName__Pack(dataStore, cancellation);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        /// <inheritdoc/>
        protected override async ValueTask OnUnpack(IDataStore dataStore, int depth, CancellationToken cancellation)
        {
            await base.OnUnpack(dataStore, depth, cancellation);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            await T_NullableEntityMemberName__Unpack(dataStore, depth, cancellation);
            //##} else {
            await T_RequiredEntityMemberName__Unpack(dataStore, depth, cancellation);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            await T_NullableBinaryMemberName__Unpack(dataStore, cancellation);
            //##} else {
            await T_RequiredBinaryMemberName__Unpack(dataStore, cancellation);
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            await T_NullableStringMemberName__Unpack(dataStore, cancellation);
            //##} else {
            await T_RequiredStringMemberName__Unpack(dataStore, cancellation);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        // -------------------- field map -----------------------------
        //  Seq.  Off.  Len.  End.  Type    Name
        //  ----  ----  ----  ----  ------- -------
        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //  T_MemberSequenceR4_  T_FieldOffsetR4_  T_FieldLengthR4_  T_MemberBELE_    T_MemberTypeL7_ T_MemberName_
        //##if(member.NullAddress is not null) {
        //        T_BitsFieldOffsetR4_  T_NullBitPositionR4_                T_MemberName_ (isNull bit)
        //##}
        //##}
        // ------------------------------------------------------------

        /// <summary>
        /// Creates a new instance of the T_EntityImplName_ entity.
        /// </summary>
        protected T_EntityImplName_(EntityMetadata metadata) : base(metadata)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
        }

        /// <summary>
        /// Creates a new instance of the T_EntityImplName_ entity.
        /// </summary>
        public T_EntityImplName_() : base(_metadata)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);

        }

        /// <summary>
        /// Creates a new instance of the T_EntityImplName_ entity by copying from the source instance.
        /// </summary>
        protected T_EntityImplName_(EntityMetadata metadata, T_EntityImplName_ source) : base(metadata, source)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            this.T_NullableCustomStructMemberName_ = source.T_NullableCustomStructMemberName_;
            //##} else {
            this.T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            this.T_RequiredCustomStructMemberName_ = source.T_RequiredCustomStructMemberName_;
            //##} else {
            this.T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_;
            //##} else {
            _T_RequiredEntityMemberName_ = source._T_RequiredEntityMemberName_;
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        /// <summary>
        /// Creates a new instance of the T_EntityImplName_ entity by copying from the source instance.
        /// </summary>
        public T_EntityImplName_(T_EntityImplName_ source) : this(_metadata, source) { }

        /// <summary>
        /// Creates a new instance of the T_EntityImplName_ entity by copying from the source interface.
        /// </summary>
        protected T_EntityImplName_(EntityMetadata metadata, T_IntfNameSpace_.T_EntityIntfName_ source) : base(metadata, source)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = _writableGlobalBlock.Slice(BlockOffset, BlockLength);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            this.T_NullableCustomStructMemberName_ = source.T_NullableCustomStructMemberName_;
            //##} else {
            this.T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            this.T_RequiredCustomStructMemberName_ = source.T_RequiredCustomStructMemberName_;
            //##} else {
            this.T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        /// <summary>
        /// Creates a new instance of the T_EntityImplName_ entity by copying from the source interface.
        /// </summary>
        public T_EntityImplName_(T_IntfNameSpace_.T_EntityIntfName_ source) : this(_metadata, source) { }

        /// <summary>
        /// Creates a new frozen instance of the T_EntityImplName_ entity by copying from the source.
        /// </summary>
        protected T_EntityImplName_(EntityMetadata metadata, ReadOnlyMemory<byte> buffer) : base(metadata, buffer)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = Memory<byte>.Empty;
        }

        /// <summary>
        /// Creates a new frozen instance of the T_EntityImplName_ entity by deserializing the received buffer.
        /// </summary>
        public T_EntityImplName_(ReadOnlyMemory<byte> buffer) : base(_metadata, buffer)
        {
            _readonlyLocalBlock = _readonlyGlobalBlock.Slice(BlockOffset, BlockLength);
            _writableLocalBlock = Memory<byte>.Empty;
        }

        //##if(false) {
        private const int T_RequiredNativeStructFieldOffset_ = 0;
        private const int T_RequiredCustomStructFieldOffset_ = 4;
        private const int T_NullableCustomStructFieldOffset_ = 8;
        private const int T_NullableNativeStructFieldOffset_ = 12;

        private const int T_NullableEntityFieldOffset_ = 64;
        private const int T_RequiredEntityFieldOffset_ = 128;

        private const int T_NullableBinaryFieldOffset_ = 256;
        private const int T_RequiredBinaryFieldOffset_ = 320;

        private const int T_NullableStringFieldOffset_ = 448;
        private const int T_RequiredStringFieldOffset_ = 512;

        private const int T_FieldLength_ = 4;
        private const bool T_IsBigEndian_ = false;
        private const int T_BitsFieldOffset_ = 0;
        private const int T_BitsFieldLength_ = 4;
        private const int T_NullBitPosition_ = 0;
        //##}
        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //##switch(member.Kind) {
        //##case MemberKind.Struct:
        //##if (member.IsNullable) {
        //##if (member.IsCustom) {
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_CustomMemberType_? T_NullableCustomStructMemberName_
        {
            get
            {
                var bits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));
                if (bits.GetBit(T_NullBitPosition_)) return null;
                T_NativeMemberType_ nativeValue = Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span);
                return T_ConverterSpace_.T_ConverterName_.ToCustom(nativeValue);
            }
            set
            {
                ThrowIfFrozen();
                Bits32 oldBits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));
                Bits32 newBits = oldBits.SetBit(T_NullBitPosition_, !value.HasValue);
                if (newBits != oldBits)
                {
                    Codec_UInt32_LE.WriteToSpan(_writableLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span, newBits.Data);
                }
                if (value.HasValue)
                {
                    T_NativeMemberType_ nativeValue = T_ConverterSpace_.T_ConverterName_.ToNative(value.Value);
                    Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span, nativeValue);
                }
                else
                {
                    _writableLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span.Clear();
                }
            }
        }
        //##} else {
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_NativeMemberType_? T_NullableNativeStructMemberName_
        {
            get
            {
                var bits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));
                if (bits.GetBit(T_NullBitPosition_)) return null;
                return Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span);
            }
            set
            {
                ThrowIfFrozen();
                Bits32 oldBits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));
                Bits32 newBits = oldBits.SetBit(T_NullBitPosition_, !value.HasValue);
                if (newBits != oldBits)
                {
                    Codec_UInt32_LE.WriteToSpan(_writableLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span, newBits.Data);
                }
                if (value.HasValue)
                {
                    Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span, value.Value);
                }
                else
                {
                    _writableLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span.Clear();
                }
            }
        }
        //##}
        //##} else {
        //##if (member.IsCustom) {
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_CustomMemberType_ T_RequiredCustomStructMemberName_
        {
            get
            {
                T_NativeMemberType_ nativeValue = Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredCustomStructFieldOffset_, T_FieldLength_).Span);
                return T_ConverterSpace_.T_ConverterName_.ToCustom(nativeValue);
            }
            set
            {
                ThrowIfFrozen();
                T_NativeMemberType_ nativeValue = T_ConverterSpace_.T_ConverterName_.ToNative(value);
                Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredCustomStructFieldOffset_, T_FieldLength_).Span, nativeValue);
            }
        }
        //##} else {
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_NativeMemberType_ T_RequiredNativeStructMemberName_
        {
            get
            {
                return Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredNativeStructFieldOffset_, T_FieldLength_).Span);
            }
            set
            {
                ThrowIfFrozen();
                Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredNativeStructFieldOffset_, T_FieldLength_).Span, value);
            }
        }
        //##}
        //##}
        //##break;
        //##case MemberKind.Entity:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableEntityMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)
        {
            var writableField = _writableLocalBlock.Slice(T_NullableEntityFieldOffset_, 64);
            if (_T_NullableEntityMemberName_ is not null) await _T_NullableEntityMemberName_.Pack(dataStore, cancellation);
            await PackData(_T_NullableEntityMemberName_?.Serialize(cancellation), writableField, dataStore);
        }
        private async ValueTask T_NullableEntityMemberName__Unpack(IDataStore dataStore, int depth, CancellationToken cancellation)
        {
            var readonlyField = _readonlyLocalBlock.Slice(T_NullableEntityFieldOffset_, 64);
            var data = await UnpackData(readonlyField, dataStore);
            _T_NullableEntityMemberName_ = null;
            if (data.HasValue)
            {
                _T_NullableEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(data.Value);
                await _T_NullableEntityMemberName_.Unpack(dataStore, depth - 1, cancellation);
            }
        }
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_
        {
            get => IfUnpacked(_T_NullableEntityMemberName_);
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_
        {
            get => IfUnpacked(_T_NullableEntityMemberName_);
            set => _T_NullableEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(value));
        }
        //##} else {
        private async ValueTask T_RequiredEntityMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)
        {
            var writableField = _writableLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64);
            if (_T_RequiredEntityMemberName_ is null)
            {
                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore, cancellation);
            }
            await _T_RequiredEntityMemberName_.Pack(dataStore, cancellation);
            await PackData(_T_RequiredEntityMemberName_.Serialize(cancellation), writableField, dataStore);
        }
        private async ValueTask T_RequiredEntityMemberName__Unpack(IDataStore dataStore, int depth, CancellationToken cancellation)
        {
            var readonlyField = _readonlyLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64);
            var data = await UnpackData(readonlyField, dataStore);
            if (data.HasValue)
            {
                _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(data.Value);
                await _T_RequiredEntityMemberName_.Unpack(dataStore, depth - 1, cancellation);
            }
            else
            {
                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore, cancellation);
            }
        }
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_RequiredEntityMemberName_ = null;
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_
        {
            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_
        {
            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(value));
        }
        //##}
        //##break;
        //##case MemberKind.Binary:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableBinaryMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)
        {
            var writableField = _writableLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64);
            await PackData(_T_NullableBinaryMemberName_?.AsMemory(), writableField, dataStore);
        }
        private async ValueTask T_NullableBinaryMemberName__Unpack(IDataStore dataStore, CancellationToken cancellation)
        {
            var readonlyField = _readonlyLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64);
            var data = await UnpackData(readonlyField, dataStore);
            _T_NullableBinaryMemberName_ = data.HasValue ? Octets.Wrap(data.Value) : null;
        }
        private Octets? _T_NullableBinaryMemberName_;
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets? T_NullableBinaryMemberName_
        {
            get => IfUnpacked(_T_NullableBinaryMemberName_);
            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_RequiredBinaryMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)
        {
            var writableField = _writableLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64);
            await PackData(_T_RequiredBinaryMemberName_.AsMemory(), writableField, dataStore);
        }
        private async ValueTask T_RequiredBinaryMemberName__Unpack(IDataStore dataStore, CancellationToken cancellation)
        {
            var readonlyField = _readonlyLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64);
            var data = await UnpackData(readonlyField, dataStore);
            _T_RequiredBinaryMemberName_ = data.HasValue ? Octets.Wrap(data.Value) : Octets.Empty;
        }
        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets T_RequiredBinaryMemberName_
        {
            get => IfUnpacked(_T_RequiredBinaryMemberName_);
            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##case MemberKind.String:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableStringMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)
        {
            var writableField = _writableLocalBlock.Slice(T_NullableStringFieldOffset_, 64);
            await PackText(_T_NullableStringMemberName_, writableField, dataStore);
        }
        private async ValueTask T_NullableStringMemberName__Unpack(IDataStore dataStore, CancellationToken cancellation)
        {
            var readonlyField = _readonlyLocalBlock.Slice(T_NullableStringFieldOffset_, 64);
            var data = await UnpackData(readonlyField, dataStore);
#if NET8_0_OR_GREATER
            _T_NullableStringMemberName_ = data.HasValue ? System.Text.Encoding.UTF8.GetString(data.Value.Span) : null;
#else
            _T_NullableStringMemberName_ = data.HasValue ? System.Text.Encoding.UTF8.GetString(data.Value.ToArray()) : null;
#endif
        }
        private string? _T_NullableStringMemberName_;
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public string? T_NullableStringMemberName_
        {
            get => IfUnpacked(_T_NullableStringMemberName_);
            set => _T_NullableStringMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_RequiredStringMemberName__Pack(IDataStore dataStore, CancellationToken cancellation)
        {
            var writableField = _writableLocalBlock.Slice(T_RequiredStringFieldOffset_, 64);
            await PackText(_T_RequiredStringMemberName_, writableField, dataStore);
        }
        private async ValueTask T_RequiredStringMemberName__Unpack(IDataStore dataStore, CancellationToken cancellation)
        {
            var readonlyField = _readonlyLocalBlock.Slice(T_RequiredStringFieldOffset_, 64);
            var data = await UnpackData(readonlyField, dataStore);
#if NET8_0_OR_GREATER
            _T_RequiredStringMemberName_ = data.HasValue ? System.Text.Encoding.UTF8.GetString(data.Value.Span) : string.Empty;
#else
            _T_RequiredStringMemberName_ = data.HasValue ? System.Text.Encoding.UTF8.GetString(data.Value.ToArray()) : string.Empty;
#endif
        }
        private string _T_RequiredStringMemberName_ = string.Empty;
        /// <inheritdoc/>
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public string T_RequiredStringMemberName_
        {
            get => IfUnpacked(_T_RequiredStringMemberName_);
            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##default:
        //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
        //##break;
        //##} // switch

        //##}

        /// <inheritdoc/>
        public bool Equals(T_EntityImplName_? other) => base.Equals(other);
        /// <inheritdoc/>
        public override bool Equals(object? obj) => obj is T_EntityImplName_ other && Equals(other);
        /// <inheritdoc/>
        public override int GetHashCode() => base.GetHashCode();
        /// <inheritdoc/>
        public static bool operator ==(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? left.Equals(right) : (right is null);
        /// <inheritdoc/>
        public static bool operator !=(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);

    }
}
//##    }
//##}
